// Curated destination pool for Globetrotter. Pure data — no React, no logic.
// Coordinates are approximate landmark positions (good to well under the
// 25 km bullseye radius, which is all the scoring needs).
export interface GeoLocation {
  name: string
  country: string
  lat: number
  lng: number
  emoji: string
  clues: string[]
}

export const LOCATIONS: GeoLocation[] = [
  {
    name: 'Eiffel Tower',
    country: 'France',
    lat: 48.858,
    lng: 2.294,
    emoji: '🗼',
    clues: [
      'You are in a temperate European capital split by a slow, romantic river.',
      'Locals carry baguettes past Haussmann façades and café terraces.',
      'A wrought-iron lattice tower from an 1889 world fair dominates the skyline.',
    ],
  },
  {
    name: 'Statue of Liberty',
    country: 'United States',
    lat: 40.689,
    lng: -74.044,
    emoji: '🗽',
    clues: [
      'You are on a tiny island in a busy harbor on the Atlantic coast of North America.',
      'Yellow cabs and a famous skyline of skyscrapers sit just across the water.',
      'A copper-green lady lifts a torch to welcome arriving ships.',
    ],
  },
  {
    name: 'Great Pyramid of Giza',
    country: 'Egypt',
    lat: 29.979,
    lng: 31.134,
    emoji: '🐪',
    clues: [
      'You are on a dusty desert plateau at the edge of a huge African metropolis.',
      'Camels plod past vendors, and a great river delta lies just to the east.',
      'Three ancient royal tombs rise from the sand beside a lion-bodied statue.',
    ],
  },
  {
    name: 'Sydney Opera House',
    country: 'Australia',
    lat: -33.857,
    lng: 151.215,
    emoji: '🎭',
    clues: [
      'You are in a sunny southern-hemisphere harbor city where December is beach season.',
      'Ferries criss-cross the bay beneath a giant steel arch bridge.',
      'White sail-shaped shells house one of the most famous concert halls on Earth.',
    ],
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    lat: -13.163,
    lng: -72.545,
    emoji: '⛰️',
    clues: [
      'You are high in a misty South American mountain range, short of breath.',
      'Llamas graze on terraces and a famous multi-day trekking trail ends here.',
      'A lost 15th-century Inca citadel clings to a ridge above a river gorge.',
    ],
  },
  {
    name: 'Taj Mahal',
    country: 'India',
    lat: 27.175,
    lng: 78.042,
    emoji: '🕌',
    clues: [
      'You are on a hot river plain in South Asia, and the traffic is chaos.',
      'Rickshaws honk past street vendors selling chai and samosas.',
      'A white marble mausoleum built by an emperor for his wife glows at dawn.',
    ],
  },
  {
    name: 'Great Wall at Badaling',
    country: 'China',
    lat: 40.432,
    lng: 116.57,
    emoji: '🧱',
    clues: [
      'You are on a ridge of green hills north of a vast East Asian capital.',
      'Watchtowers march along the mountain crests as far as you can see.',
      'You are standing on a stone fortification thousands of kilometers long.',
    ],
  },
  {
    name: 'Christ the Redeemer',
    country: 'Brazil',
    lat: -22.952,
    lng: -43.21,
    emoji: '⛪',
    clues: [
      'You are on a granite peak above a South American beach city famous for carnival.',
      'Below you, samba drifts up from Copacabana and Ipanema.',
      'An enormous art-deco statue spreads its arms over the bay.',
    ],
  },
  {
    name: 'Colosseum',
    country: 'Italy',
    lat: 41.89,
    lng: 12.492,
    emoji: '🏛️',
    clues: [
      'You are in a Mediterranean capital where every street corner hides ruins.',
      'Espresso is drunk standing up, and scooters swarm the cobblestones.',
      'A 2,000-year-old elliptical amphitheater once hosted gladiators here.',
    ],
  },
  {
    name: 'Big Ben',
    country: 'United Kingdom',
    lat: 51.5,
    lng: -0.125,
    emoji: '🕰️',
    clues: [
      'You are in a drizzly island capital where traffic drives on the left.',
      'Red double-decker buses roll past a river lined with government buildings.',
      'A famous clock tower chimes beside a gothic parliament.',
    ],
  },
  {
    name: 'Mount Fuji',
    country: 'Japan',
    lat: 35.361,
    lng: 138.727,
    emoji: '🗻',
    clues: [
      'You are on an island nation in East Asia where bullet trains glide past.',
      'Vending machines and torii gates dot the villages around a great lake.',
      'A perfectly symmetrical snow-capped volcano towers over everything.',
    ],
  },
  {
    name: 'Santorini',
    country: 'Greece',
    lat: 36.393,
    lng: 25.461,
    emoji: '🌅',
    clues: [
      'You are on a crescent-shaped Mediterranean island formed by a volcanic eruption.',
      'Donkeys carry visitors up cliff paths from a deep blue caldera.',
      'Whitewashed houses with blue domes spill down the cliffs at sunset.',
    ],
  },
  {
    name: 'Petra',
    country: 'Jordan',
    lat: 30.329,
    lng: 35.444,
    emoji: '🏜️',
    clues: [
      'You are walking through a narrow desert canyon in the Middle East.',
      'Bedouin guides offer rides past tombs cut into rose-colored rock.',
      'The canyon opens onto a treasury façade carved into the cliff itself.',
    ],
  },
  {
    name: 'Angkor Wat',
    country: 'Cambodia',
    lat: 13.412,
    lng: 103.867,
    emoji: '🛕',
    clues: [
      'You are in humid Southeast Asian jungle, and strangler figs swallow old stones.',
      'Monks in orange robes walk causeways over a vast moat.',
      'The largest religious monument on Earth — a Khmer temple city — surrounds you.',
    ],
  },
  {
    name: 'Golden Gate Bridge',
    country: 'United States',
    lat: 37.82,
    lng: -122.478,
    emoji: '🌉',
    clues: [
      'You are on a foggy Pacific-coast strait beside a hilly tech-obsessed city.',
      'Cable cars climb the streets and sea lions bark at the piers.',
      'An "international orange" suspension bridge vanishes into the mist.',
    ],
  },
  {
    name: 'Niagara Falls',
    country: 'Canada',
    lat: 43.08,
    lng: -79.074,
    emoji: '💦',
    clues: [
      'You are on a border between two large North American countries.',
      'Everyone around you is wearing a plastic poncho on a tour boat.',
      'A horseshoe-shaped curtain of water thunders over the edge.',
    ],
  },
  {
    name: 'Stonehenge',
    country: 'United Kingdom',
    lat: 51.179,
    lng: -1.826,
    emoji: '🪨',
    clues: [
      'You are on a windswept green plain in northwestern Europe.',
      'Sheep graze around earthworks older than the pyramids.',
      'A prehistoric ring of standing stones aligns with the solstice sun.',
    ],
  },
  {
    name: 'Sagrada Família',
    country: 'Spain',
    lat: 41.404,
    lng: 2.174,
    emoji: '🏗️',
    clues: [
      'You are in a Mediterranean city laid out on a giant grid with chamfered corners.',
      'Tapas bars line boulevards full of Gaudí’s wavy architecture.',
      'A basilica has been under construction here since 1882 — and still is.',
    ],
  },
  {
    name: 'Burj Khalifa',
    country: 'United Arab Emirates',
    lat: 25.197,
    lng: 55.274,
    emoji: '🏙️',
    clues: [
      'You are in a scorching Gulf city that grew from desert in a single generation.',
      'Indoor ski slopes and gold souks share the same skyline.',
      'You crane your neck at the tallest building humans have ever built.',
    ],
  },
  {
    name: 'Table Mountain',
    country: 'South Africa',
    lat: -33.963,
    lng: 18.409,
    emoji: '🏔️',
    clues: [
      'You are at the meeting point of two oceans at the tip of a continent.',
      'Penguins waddle on nearby beaches while a cable car climbs behind the city.',
      'A perfectly flat-topped mountain wears a "tablecloth" of cloud.',
    ],
  },
  {
    name: 'Serengeti Plains',
    country: 'Tanzania',
    lat: -2.333,
    lng: 34.833,
    emoji: '🦁',
    clues: [
      'You are on endless golden savanna just south of the equator in East Africa.',
      'A million wildebeest rumble past your safari jeep in the great migration.',
      'Lions doze under acacia trees in Africa’s most famous national park.',
    ],
  },
  {
    name: 'Victoria Falls',
    country: 'Zambia',
    lat: -17.924,
    lng: 25.857,
    emoji: '🌊',
    clues: [
      'You are in southern Africa and can hear a roar from kilometers away.',
      'Locals call this place "the smoke that thunders".',
      'A river over a kilometer wide plunges into a basalt gorge on a national border.',
    ],
  },
  {
    name: 'Rapa Nui Moai',
    country: 'Chile',
    lat: -27.113,
    lng: -109.35,
    emoji: '🗿',
    clues: [
      'You are on one of the most remote inhabited islands in the Pacific Ocean.',
      'The nearest continent is over 3,500 km away to the east.',
      'Hundreds of giant stone heads gaze inland across the grassy slopes.',
    ],
  },
  {
    name: 'Grand Canyon',
    country: 'United States',
    lat: 36.107,
    lng: -112.113,
    emoji: '🏜️',
    clues: [
      'You are in the arid southwest of North America, far from any coast.',
      'Condors ride thermals over layered red rock.',
      'A river has carved a gorge here nearly two kilometers deep.',
    ],
  },
  {
    name: 'Lake Louise',
    country: 'Canada',
    lat: 51.417,
    lng: -116.217,
    emoji: '🏞️',
    clues: [
      'You are high in the Rocky Mountains of a huge, sparsely populated country.',
      'Canoes glide across impossibly turquoise glacier water.',
      'A grand railway hotel faces a wall of ice at the end of the lake.',
    ],
  },
  {
    name: 'Reykjavik',
    country: 'Iceland',
    lat: 64.147,
    lng: -21.94,
    emoji: '🌋',
    clues: [
      'You are on a volcanic North Atlantic island just below the Arctic Circle.',
      'Locals bathe outdoors in geothermal water while it snows.',
      'This is the northernmost capital city of a sovereign state.',
    ],
  },
  {
    name: 'Red Square',
    country: 'Russia',
    lat: 55.754,
    lng: 37.62,
    emoji: '🏰',
    clues: [
      'You are in a vast, cold capital that spans Europe’s eastern edge.',
      'The metro stations look like underground palaces.',
      'Swirling candy-colored onion domes rise beside a fortress wall.',
    ],
  },
  {
    name: 'Hagia Sophia',
    country: 'Turkey',
    lat: 41.009,
    lng: 28.98,
    emoji: '🕌',
    clues: [
      'You are in the only major city that straddles two continents.',
      'Ferries cross a strait between bazaars, minarets, and tea gardens.',
      'A 1,500-year-old domed basilica-turned-mosque anchors the old town.',
    ],
  },
  {
    name: 'Marrakesh Medina',
    country: 'Morocco',
    lat: 31.626,
    lng: -7.989,
    emoji: '🏺',
    clues: [
      'You are in a maze of alleys in North Africa, with snowy peaks on the horizon.',
      'Snake charmers and spice pyramids fill a famous evening square.',
      'The walls of this old imperial city glow dusty red at sunset.',
    ],
  },
  {
    name: 'Uluru',
    country: 'Australia',
    lat: -25.345,
    lng: 131.037,
    emoji: '🦘',
    clues: [
      'You are in the dead center of a huge, dry southern continent.',
      'Kangaroos rest in the shade of desert oaks in the red outback.',
      'A single sandstone monolith, sacred to its traditional owners, changes color at dusk.',
    ],
  },
  {
    name: 'Neuschwanstein Castle',
    country: 'Germany',
    lat: 47.558,
    lng: 10.75,
    emoji: '🏰',
    clues: [
      'You are in green alpine foothills in central Europe.',
      'Cowbells clank in the valleys below a fairy-tale ridge.',
      'A 19th-century king built the turreted castle that inspired a theme-park logo.',
    ],
  },
  {
    name: 'Amsterdam Canals',
    country: 'Netherlands',
    lat: 52.373,
    lng: 4.892,
    emoji: '🚲',
    clues: [
      'You are below sea level in a flat European country of windmills and dikes.',
      'Thousands of bicycles rattle over bridges past narrow gabled houses.',
      'Ring-shaped 17th-century canals define this famously liberal capital.',
    ],
  },
  {
    name: 'Gyeongbokgung Palace',
    country: 'South Korea',
    lat: 37.579,
    lng: 126.977,
    emoji: '🏯',
    clues: [
      'You are in a hyper-modern East Asian capital wedged between mountains.',
      'Visitors in rented hanbok pose for photos beneath painted eaves.',
      'A Joseon-dynasty royal palace sits at the head of a grand boulevard.',
    ],
  },
  {
    name: 'Grand Palace of Bangkok',
    country: 'Thailand',
    lat: 13.75,
    lng: 100.492,
    emoji: '🍜',
    clues: [
      'You are in a steamy Southeast Asian capital of tuk-tuks and street food.',
      'Long-tail boats race along a river past golden spires.',
      'A dazzling royal compound houses a tiny, revered Emerald Buddha.',
    ],
  },
  {
    name: 'Marina Bay Sands',
    country: 'Singapore',
    lat: 1.284,
    lng: 103.86,
    emoji: '🌴',
    clues: [
      'You are in a spotless equatorial city-state at the tip of a peninsula.',
      'Hawker centers serve laksa beneath futuristic "supertree" gardens.',
      'A ship-shaped skypark bridges three hotel towers above the bay.',
    ],
  },
  {
    name: 'Tegallalang Rice Terraces',
    country: 'Indonesia',
    lat: -8.432,
    lng: 115.279,
    emoji: '🌾',
    clues: [
      'You are on a lush volcanic island in a vast equatorial archipelago.',
      'Offerings of flowers sit outside Hindu temples between the palms.',
      'Emerald rice paddies staircase down the hillsides of this famous island.',
    ],
  },
  {
    name: 'Everest Base Camp',
    country: 'Nepal',
    lat: 27.988,
    lng: 86.925,
    emoji: '🎏',
    clues: [
      'You are gasping for air at over 5,000 meters in a Himalayan kingdom.',
      'Yaks haul gear past prayer flags and stone stupas.',
      'Climbers gather here before attempting the highest summit on Earth.',
    ],
  },
  {
    name: 'Registan Square',
    country: 'Uzbekistan',
    lat: 39.655,
    lng: 66.976,
    emoji: '🐫',
    clues: [
      'You are in Central Asia on the ancient Silk Road between deserts.',
      'Melon sellers trade beside turquoise-tiled madrasahs.',
      'Three monumental tiled schools frame the heart of Samarkand.',
    ],
  },
  {
    name: 'Rovaniemi',
    country: 'Finland',
    lat: 66.503,
    lng: 25.729,
    emoji: '🎅',
    clues: [
      'You are in a snowy Nordic forest right on the Arctic Circle.',
      'Reindeer sleds glide beneath the northern lights.',
      'This town markets itself as the official hometown of Santa Claus.',
    ],
  },
  {
    name: 'Geirangerfjord',
    country: 'Norway',
    lat: 62.101,
    lng: 7.206,
    emoji: '⛴️',
    clues: [
      'You are in Scandinavia, sailing between kilometer-high cliff walls.',
      'Waterfalls named after brides and their suitors plunge into dark water.',
      'This UNESCO-listed fjord is the poster child of its country.',
    ],
  },
  {
    name: 'Old Havana',
    country: 'Cuba',
    lat: 23.137,
    lng: -82.359,
    emoji: '🚗',
    clues: [
      'You are on the largest island in the Caribbean.',
      'Classic 1950s American cars cruise past pastel colonial arcades.',
      'Son cubano drifts from bars along the Malecón seawall.',
    ],
  },
  {
    name: 'Chichén Itzá',
    country: 'Mexico',
    lat: 20.684,
    lng: -88.568,
    emoji: '🐍',
    clues: [
      'You are on a hot limestone peninsula dotted with freshwater sinkholes.',
      'At the equinox, a serpent of shadow slithers down a staircase here.',
      'A stepped Maya pyramid dominates this ancient ball-playing city.',
    ],
  },
  {
    name: 'Galápagos Islands',
    country: 'Ecuador',
    lat: -0.777,
    lng: -91.142,
    emoji: '🐢',
    clues: [
      'You are on a volcanic archipelago straddling the equator in the Pacific.',
      'Iguanas swim in the surf and boobies have bright blue feet.',
      'Giant tortoises here helped inspire the theory of evolution.',
    ],
  },
  {
    name: 'Torres del Paine',
    country: 'Chile',
    lat: -50.942,
    lng: -73.407,
    emoji: '🦙',
    clues: [
      'You are near the stormy southern tip of South America.',
      'Guanacos graze beneath glaciers while condors circle overhead.',
      'Three granite towers give this Patagonian park its name.',
    ],
  },
  {
    name: 'Timbuktu',
    country: 'Mali',
    lat: 16.766,
    lng: -3.003,
    emoji: '📜',
    clues: [
      'You are at the southern edge of the Sahara, near a great river bend.',
      'Salt caravans still arrive at this legendary trading town.',
      'Mud-brick mosques guard ancient manuscript libraries.',
    ],
  },
  {
    name: 'Antarctic Peninsula',
    country: 'Antarctica',
    lat: -64.774,
    lng: -64.053,
    emoji: '🐧',
    clues: [
      'You are on the coldest, driest, windiest continent on Earth.',
      'Penguin colonies squabble on the shore between blue icebergs.',
      'Research stations are the only settlements for thousands of kilometers.',
    ],
  },
  {
    name: 'Bora Bora',
    country: 'French Polynesia',
    lat: -16.5,
    lng: -151.742,
    emoji: '🏝️',
    clues: [
      'You are in the South Pacific, roughly halfway between South America and Australia.',
      'Overwater bungalows ring a lagoon in every shade of blue.',
      'A jagged extinct volcano rises from the middle of this honeymoon island.',
    ],
  },
  {
    name: 'Hobbiton',
    country: 'New Zealand',
    lat: -37.872,
    lng: 175.683,
    emoji: '🐑',
    clues: [
      'You are on rolling green sheep pasture on a Pacific island nation.',
      'This country has ten times more sheep than people.',
      'Round doors are set into the hillsides of a famous movie set.',
    ],
  },
  {
    name: 'La Boca',
    country: 'Argentina',
    lat: -34.635,
    lng: -58.363,
    emoji: '💃',
    clues: [
      'You are in a South American capital that loves steak and stays up very late.',
      'Tango dancers perform between houses painted in leftover ship paint.',
      'This colorful dockside barrio is home to a famous blue-and-gold football club.',
    ],
  },
  {
    name: 'Alfama, Lisbon',
    country: 'Portugal',
    lat: 38.714,
    lng: -9.139,
    emoji: '🚋',
    clues: [
      'You are in Europe’s westernmost mainland capital, on a wide river mouth.',
      'Yellow trams grind up tiled alleys as fado drifts from taverns.',
      'Custard tarts and a hilltop Moorish castle complete the postcard.',
    ],
  },
]
