// Offline reserve deck for Random World — generated by
// scripts/generate-random-world-reserve.mjs. Do not hand-edit.
//
// Freely licensed, geotagged 2:1 photospheres from Wikimedia Commons'
// "Category:360° panoramas", used when the Commons API is unreachable or
// rate-limited at play time so the mode always has somewhere to drop you.
// Attribution travels with each entry and is shown on the panorama.

export interface ReservePanorama {
  lat: number
  lng: number
  url: string
  page: string
  author: string
  license: string
}

export const RESERVE_PANORAMAS: ReservePanorama[] = [
  {
    lat: 33.538107,
    lng: 130.450621,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Fukuoka-shi_Nakoku%2C_House_A_360-degree.jpg/3840px-Fukuoka-shi_Nakoku%2C_House_A_360-degree.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Fukuoka-shi_Nakoku%2C_House_A_360-degree.jpg',
    author: 'AsPJT',
    license: 'CC0',
  },
  {
    lat: 74.501606,
    lng: -20.583192,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Mapillary_%28b0PzAnpflQGCaMHw4di8xJ%29_%28GreenlandEcosystemMonitoring%29_2021-09-02_15H16mn08s000.jpg/3840px-Mapillary_%28b0PzAnpflQGCaMHw4di8xJ%29_%28GreenlandEcosystemMonitoring%29_2021-09-02_15H16mn08s000.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(b0PzAnpflQGCaMHw4di8xJ)_(GreenlandEcosystemMonitoring)_2021-09-02_15H16mn08s000.jpg',
    author: 'GreenlandEcosystemMonitoring',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 59.321377,
    lng: 18.068058,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Mapillary_%280McOZ7k5WEsDlNjrxgSw3I%29_%28bruno360%29_2025-06-21_09H14M36S816.jpg/3840px-Mapillary_%280McOZ7k5WEsDlNjrxgSw3I%29_%28bruno360%29_2025-06-21_09H14M36S816.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(0McOZ7k5WEsDlNjrxgSw3I)_(bruno360)_2025-06-21_09H14M36S816.jpg',
    author: 'bruno360',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 47.692685,
    lng: 9.274167,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/DayEnvironmentHDRI070_16K-TONEMAPPED.jpg/3840px-DayEnvironmentHDRI070_16K-TONEMAPPED.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:DayEnvironmentHDRI070_16K-TONEMAPPED.jpg',
    author: 'ambientCG / Lennart Demes',
    license: 'CC0',
  },
  {
    lat: 57.154461,
    lng: -2.099732,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mapillary_%28Walk-Wheel-Cycle-Trust%29_2023-10-02_09H51M35S500_%28210136208783927_at_eqvormIGOyNYXpb7iSRl9g_with_Pilot_One%29.jpg/3840px-Mapillary_%28Walk-Wheel-Cycle-Trust%29_2023-10-02_09H51M35S500_%28210136208783927_at_eqvormIGOyNYXpb7iSRl9g_with_Pilot_One%29.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(Walk-Wheel-Cycle-Trust)_2023-10-02_09H51M35S500_(210136208783927_at_eqvormIGOyNYXpb7iSRl9g_with_Pilot_One).jpg',
    author: 'Walk-Wheel-Cycle-Trust',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 44.440088,
    lng: 26.093139,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Mapillary_%28900891718419110%2C_xBgZtDoIYCmMdlAP5hO7ur%29_%28Pill0r360%29_2023-09-05_08H46M20S691.jpg/3840px-Mapillary_%28900891718419110%2C_xBgZtDoIYCmMdlAP5hO7ur%29_%28Pill0r360%29_2023-09-05_08H46M20S691.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(900891718419110%2C_xBgZtDoIYCmMdlAP5hO7ur)_(Pill0r360)_2023-09-05_08H46M20S691.jpg',
    author: 'Pill0r360',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 49.27323,
    lng: -123.11103,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Vancouver%2C_BC%2C_Canada_-_panoramio.jpg/3840px-Vancouver%2C_BC%2C_Canada_-_panoramio.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Vancouver%2C_BC%2C_Canada_-_panoramio.jpg',
    author: 'Ryan Adams',
    license: 'CC BY-SA 3.0',
  },
  {
    lat: 51.907287,
    lng: 4.490073,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Mapillary_%28500659789112934%2C_2xLVDRJEoAHer831c5Ffzi%29_%28tumblecow%29_2024-07-18_15H43M59S525.jpg/3840px-Mapillary_%28500659789112934%2C_2xLVDRJEoAHer831c5Ffzi%29_%28tumblecow%29_2024-07-18_15H43M59S525.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(500659789112934%2C_2xLVDRJEoAHer831c5Ffzi)_(tumblecow)_2024-07-18_15H43M59S525.jpg',
    author: 'tumblecow',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 33.823086,
    lng: -116.507472,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Palm_Springs_International_Airport_concourse_360-degree_view.jpg/3840px-Palm_Springs_International_Airport_concourse_360-degree_view.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Palm_Springs_International_Airport_concourse_360-degree_view.jpg',
    author: 'Sdkb',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 35.731194,
    lng: 140.227444,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Yamanosaki_Hachiman_Jinja%2C_Honden.jpg/3840px-Yamanosaki_Hachiman_Jinja%2C_Honden.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Yamanosaki_Hachiman_Jinja%2C_Honden.jpg',
    author: 'AsPJT',
    license: 'CC0',
  },
  {
    lat: 55.692051,
    lng: 37.536919,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Gagarinsky_District%2C_Moscow%2C_Russia_-_panoramio_%28188%29.jpg/3840px-Gagarinsky_District%2C_Moscow%2C_Russia_-_panoramio_%28188%29.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Gagarinsky_District%2C_Moscow%2C_Russia_-_panoramio_(188).jpg',
    author: 'Svetlov Artem',
    license: 'CC BY 3.0',
  },
  {
    lat: 50.841754,
    lng: 0.495361,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Galley_Hill_Open_Space%2C_Bexhill_%28360_panorama%29.jpg/3840px-Galley_Hill_Open_Space%2C_Bexhill_%28360_panorama%29.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Galley_Hill_Open_Space%2C_Bexhill_(360_panorama).jpg',
    author: 'Alexis Markwick',
    license: 'CC BY-SA 3.0',
  },
  {
    lat: 51.708603,
    lng: 18.626796,
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Warta_z_lotu_ptaka_od_wschodu2.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Warta_z_lotu_ptaka_od_wschodu2.jpg',
    author: 'Anwar2',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 24.988631,
    lng: 121.528881,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/R0011976_Xiulang_Bridge.jpg/3840px-R0011976_Xiulang_Bridge.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:R0011976_Xiulang_Bridge.jpg',
    author: 'Irvin Chen',
    license: 'CC BY-SA 2.0',
  },
  {
    lat: 24.142893,
    lng: -110.311479,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Panorama_esf%C3%A9rico_360_de_la_ciudad_de_La_Paz%2C_Baja_California%2C_Sur.jpg/3840px-Panorama_esf%C3%A9rico_360_de_la_ciudad_de_La_Paz%2C_Baja_California%2C_Sur.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Panorama_esf%C3%A9rico_360_de_la_ciudad_de_La_Paz%2C_Baja_California%2C_Sur.jpg',
    author: 'ProtoplasmaKid',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 51.33272,
    lng: 12.36805,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Leipzig-Bibliotheca-Albertina-gro%C3%9Fer-Lesesaal-S%C3%BCdseite-IMG_6098-8x5B-360x180G-PanoS-22-02-2025.jpg/3840px-Leipzig-Bibliotheca-Albertina-gro%C3%9Fer-Lesesaal-S%C3%BCdseite-IMG_6098-8x5B-360x180G-PanoS-22-02-2025.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Leipzig-Bibliotheca-Albertina-gro%C3%9Fer-Lesesaal-S%C3%BCdseite-IMG_6098-8x5B-360x180G-PanoS-22-02-2025.jpg',
    author: 'Joachim Köhler',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 31.630318,
    lng: -8.012251,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Mapillary_%28601083067539176%2C_oKjl-DJ9ZrT-YpVDYyOKUw%29_%28navcities%29_2019-12-21_12H48M51S000.jpg/3840px-Mapillary_%28601083067539176%2C_oKjl-DJ9ZrT-YpVDYyOKUw%29_%28navcities%29_2019-12-21_12H48M51S000.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(601083067539176%2C_oKjl-DJ9ZrT-YpVDYyOKUw)_(navcities)_2019-12-21_12H48M51S000.jpg',
    author: 'navcities',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 30.016376,
    lng: 31.419082,
    url: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Mapillary_%28600503231954799%2C_adJ0pieNT7hQLcsFgbknA8%29_%28Twospatial%29_2022-12-02_09H42M29S660.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(600503231954799%2C_adJ0pieNT7hQLcsFgbknA8)_(Twospatial)_2022-12-02_09H42M29S660.jpg',
    author: 'Twospatial',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 43.634719,
    lng: -110.791133,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PANO_20160730_100959.jpg/3840px-PANO_20160730_100959.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:PANO_20160730_100959.jpg',
    author: 'Daniel Schwen',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 47.9212,
    lng: 14.34091,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Im_Tal_der_Feitelmacher%2C_Trattenbach_-_Drechslerei_am_Erlach_-_Panorama_%283%29.jpg/3840px-Im_Tal_der_Feitelmacher%2C_Trattenbach_-_Drechslerei_am_Erlach_-_Panorama_%283%29.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Im_Tal_der_Feitelmacher%2C_Trattenbach_-_Drechslerei_am_Erlach_-_Panorama_(3).jpg',
    author: '© 1971markus',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 28.005181,
    lng: 86.859497,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Mapillary_%28gallimaps%29_2024-04-30_06H40M27S000_%282774849299358957_at_rRikwTcQ7W9zA8F5x4SpIe_with_Labpano_Pilot_Era%29.jpg/3840px-Mapillary_%28gallimaps%29_2024-04-30_06H40M27S000_%282774849299358957_at_rRikwTcQ7W9zA8F5x4SpIe_with_Labpano_Pilot_Era%29.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(gallimaps)_2024-04-30_06H40M27S000_(2774849299358957_at_rRikwTcQ7W9zA8F5x4SpIe_with_Labpano_Pilot_Era).jpg',
    author: 'gallimaps',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 42.240002,
    lng: -8.724907,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Mapillary_%284009550739256636%2C_b5BMeUWkFfJL0aPSgOucdr%29_%28EAPI%29_2025-07-10_07H49M59S830.jpg/3840px-Mapillary_%284009550739256636%2C_b5BMeUWkFfJL0aPSgOucdr%29_%28EAPI%29_2025-07-10_07H49M59S830.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(4009550739256636%2C_b5BMeUWkFfJL0aPSgOucdr)_(EAPI)_2025-07-10_07H49M59S830.jpg',
    author: 'EAPI',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 32.775035,
    lng: -96.7975,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mapillary_%28500288295173900%2C_tUYw6a5FZSpfDmQ9NXykPA%29_%28kaart_360%29_2022-05-21_14H49M10S000.jpg/3840px-Mapillary_%28500288295173900%2C_tUYw6a5FZSpfDmQ9NXykPA%29_%28kaart_360%29_2022-05-21_14H49M10S000.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(500288295173900%2C_tUYw6a5FZSpfDmQ9NXykPA)_(kaart_360)_2022-05-21_14H49M10S000.jpg',
    author: 'kaart_360',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 28.456855,
    lng: -16.25169,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Mapillary_%284009721489134798%2C_F4NLxF8n6lMvjz9cK7FZPw%29_%28javiersanp%29_2019-11-01_15H25M15S000.jpg/3840px-Mapillary_%284009721489134798%2C_F4NLxF8n6lMvjz9cK7FZPw%29_%28javiersanp%29_2019-11-01_15H25M15S000.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(4009721489134798%2C_F4NLxF8n6lMvjz9cK7FZPw)_(javiersanp)_2019-11-01_15H25M15S000.jpg',
    author: 'javiersanp',
    license: 'CC BY-SA 4.0',
  },
  {
    lat: 14.603716,
    lng: 120.982144,
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Mapillary_%28500164572541641%2C_FinWsDYmRS1GK9cBU4azpJ%29_%28kaartcam%29_2024-05-05_09H34M44S000.jpg/3840px-Mapillary_%28500164572541641%2C_FinWsDYmRS1GK9cBU4azpJ%29_%28kaartcam%29_2024-05-05_09H34M44S000.jpg',
    page: 'https://commons.wikimedia.org/wiki/File:Mapillary_(500164572541641%2C_FinWsDYmRS1GK9cBU4azpJ)_(kaartcam)_2024-05-05_09H34M44S000.jpg',
    author: 'kaartcam',
    license: 'CC BY-SA 4.0',
  },
]
