// Cards Against Humanity card data
// Source: @bixelpitch/cah-cards (CC BY-NC-SA 2.0)
// Base game + all official expansions

export interface BlackCard {
  text: string
  pick: number
}

export const BLACK_CARDS: BlackCard[] = [
  {
    text: 'Siskel and Ebert have panned ___ as "poorly conceived" and "sloppily executed."',
    pick: 1,
  },
  { text: 'Up next on Nickelodeon: "Clarissa Explains ___."', pick: 1 },
  { text: "I'm a bitch, I'm a lover, I'm a child, I'm ___.", pick: 1 },
  { text: 'How did Stella get her groove back?', pick: 1 },
  { text: 'Believe it or not, Jim Carrey can do a dead-on impression of ___.', pick: 1 },
  {
    text: "It's Morphin' Time! Mastodon! Pterodactyl! Triceratops! Sabertooth Tiger! ___!",
    pick: 1,
  },
  { text: 'Tonight on SNICK: "Are You Afraid of ___?"', pick: 1 },
  { text: "Hey Reddit! I'm ___. Ask me anything.", pick: 1 },
  { text: "Introducing X-treme Baseball! It's like baseball, but with ___!", pick: 1 },
  { text: "What is Batman's guilty pleasure.", pick: 1 },
  { text: 'TSA guidelines now prohibit ___ on airplanes.', pick: 1 },
  { text: 'When Pharaoh remained unmoved, Moses called down a Plague of ___.', pick: 1 },
  { text: 'Just once, I\'d like to hear you say "Thanks, Mom. Thanks for ___."', pick: 1 },
  { text: 'Daddy, why is mommy crying?', pick: 1 },
  { text: 'When I was tripping on acid, ___ turned into ___.', pick: 2 },
  { text: 'Next from J. K. Rowling: Harry Potter and the Chamber of ___.', pick: 1 },
  { text: "That's right, I killed ___. How, you ask? ___.", pick: 2 },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of ___.", pick: 1 },
  { text: 'And the Academy Award for ___ goes to ___.', pick: 2 },
  { text: '50% of all marriages end in ___.', pick: 1 },
  {
    text: 'My fellow Americans: Before this decade is out, we will have ___ on the moon!',
    pick: 1,
  },
  {
    text: "This season at Steppenwolf, Samuel Beckett's classic existential play: Waiting for ___.",
    pick: 1,
  },
  { text: 'Instead of coal, Santa now gives the bad children ___.', pick: 1 },
  { text: "Dude, do not go in that bathroom. There's ___ in there.", pick: 1 },
  { text: 'How did I lose my virginity?', pick: 1 },
  { text: "It's a pity that kids these days are all getting involved with ___.", pick: 1 },
  { text: 'Step 1: ___.\nStep 2: ___.\nStep 3: Profit.', pick: 2 },
  {
    text: 'Life for American Indians was forever changed when the White Man introduced them to ___.',
    pick: 1,
  },
  { text: "What's Teach For America using to inspire inner city students to succeed?", pick: 1 },
  { text: "Mabe she's born with it. Maybe it's ___.", pick: 1 },
  { text: 'What is George W. Bush thinking about right now?', pick: 1 },
  { text: "___. Betcha can't have just one!", pick: 1 },
  { text: "Kids, I don't need drugs to get high. I'm high on ___.", pick: 1 },
  { text: 'For my next trick, I will pull ___ out of ___.', pick: 2 },
  {
    text: 'While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ___.',
    pick: 1,
  },
  { text: 'White people like ___.', pick: 1 },
  { text: '___ is a slippery slope that leads to ___.', pick: 2 },
  { text: 'Why do I hurt all over?', pick: 1 },
  { text: 'A romantic, candle lit dinner would be incomplete without ___.', pick: 1 },
  {
    text: 'In the Disney Channel Original Movie, Hannah Montana struggles with ___ for the first time.',
    pick: 1,
  },
  { text: "What's my secret power?", pick: 1 },
  { text: "I'm going on a cleanse this week. Nothing but kale juice and ___.", pick: 1 },
  { text: '___ + ___\\n= ___.', pick: 3 },
  { text: 'Just saw this upsetting video! Please retweet!! #stop___', pick: 1 },
  {
    text: 'Fun tip! When your man asks you to go down on him, try surprising him with ___ instead.',
    pick: 1,
  },
  { text: 'The class field trip was completely ruined by ___.', pick: 1 },
  { text: "What's a girl's best friend?", pick: 1 },
  { text: "Dear Abby,\\nI'm having some trouble with ___ and would like your advice.", pick: 1 },
  {
    text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that ___ had really been ___ all along.",
    pick: 2,
  },
  { text: 'When I am President, I will create the Department of ___.', pick: 1 },
  { text: 'What are my parents hiding from me?', pick: 1 },
  {
    text: "I'm no doctor but I'm pretty sure what you're suffering from is called \"___.\"",
    pick: 1,
  },
  { text: "What's there a ton of in heaven?", pick: 1 },
  {
    text: "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ___.",
    pick: 1,
  },
  { text: 'What will always get you laid?', pick: 1 },
  { text: 'What never fails to liven up the party?', pick: 1 },
  { text: 'IF you like ___, YOU MIGHT BE A REDNECK.', pick: 1 },
  { text: 'Make a haiku.', pick: 1 },
  { text: 'What made my first kiss so awkward?', pick: 1 },
  {
    text: "They said we were crazy. They said we couldn't put ___ inside of ___. They were wrong.",
    pick: 2,
  },
  { text: 'Lifetime® presents "___: the Story of ___."', pick: 2 },
  { text: '___: kid-tested, mother-approved.', pick: 1 },
  { text: "Why can't I sleep at night?", pick: 1 },
  {
    text: "Hey guys, welcome to Chili's! Would you like to start the night off right with ___?",
    pick: 1,
  },
  { text: "I got 99 problems but ___ ain't one.", pick: 1 },
  { text: "___. It's a trap!", pick: 1 },
  {
    text: "Bravo's new reality show features eight washed-up celebrities living with ___.",
    pick: 1,
  },
  { text: "What's that smell?", pick: 1 },
  { text: 'After eight years in the White House, how is Obama finally letting loose?', pick: 1 },
  {
    text: 'This is the way the world ends\\nThis is the way the world ends\\nNot with a bang but with ___.',
    pick: 1,
  },
  { text: 'Coming to Broadway this season, ___: The Musical.', pick: 1 },
  { text: 'What would grandma find disturbing, yet oddly charming?', pick: 1 },
  { text: '___. That was so metal.', pick: 1 },
  { text: 'I never truly understood ___ until I encountered ___.', pick: 2 },
  { text: 'During sex, I like to think about ___.', pick: 1 },
  { text: 'Here is the church\\nHere is the steeple\\nOpen the doors And there is ___.', pick: 1 },
  { text: 'But before I kill you, Mr. Bond, I must show you ___.', pick: 1 },
  {
    text: 'A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ___.',
    pick: 1,
  },
  { text: "Introducing the amazing superhero/sidekick duo! It's ___ and ___!", pick: 2 },
  { text: 'What ended my last relationship?', pick: 1 },
  { text: "What's that sound?", pick: 1 },
  {
    text: "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ___.",
    pick: 1,
  },
  { text: 'Why am I sticky?', pick: 1 },
  { text: 'Next on ESPN2: The World Series of ___.', pick: 1 },
  { text: 'When I am a billionaire, I shall erect a 50-foot statue to commemorate ___.', pick: 1 },
  {
    text: 'Military historians remember Alexander the Great for his brilliant use of ___ against the Persians.',
    pick: 1,
  },
  { text: 'War! What is it good for?', pick: 1 },
  {
    text: 'In an attempt to reach a wider audience, the Royal Ontario Museum has opened an interactive exhibit on ___.',
    pick: 1,
  },
  { text: "What's the Canadian government using to inspire rural students to suceed?", pick: 1 },
  {
    text: 'in the next Bob and Doug McKenzie adventure, they have to find ___ to uncover a sinister plot involving ___ and ___.',
    pick: 3,
  },
  { text: 'Air canada guidelines now prohibit ___ on airplanes.', pick: 1 },
  { text: 'CTV presents ___, the store of ___.', pick: 2 },
  { text: 'In Vancouver it is now legal to ___.', pick: 1 },
  { text: 'O Canada, we stand on guard for ___.', pick: 1 },
  { text: 'If ___ came in two-fours, Canada would be more ___.', pick: 2 },
  {
    text: 'After unifying the GST and PST, the Government can now afford to provide ___ for ___.',
    pick: 2,
  },
  {
    text: 'Papa, come quickly! There, in the garden! Do you see ___? Tell me you see it, Papa!',
    pick: 1,
  },
  {
    text: "Attention students! Principal Butthead is at home recovering from ___. We hope he'll be back soon.",
    pick: 1,
  },
  {
    text: "I'm sorry, Jordan, but that's not an acceptable Science Fair project. That's just ___.",
    pick: 1,
  },
  {
    text: 'The warm August air was filled with change. Things were different, for Kayla was now ___.',
    pick: 1,
  },
  {
    text: "This is gonna be the best sleepover ever. Once Mom goes to bed, it's time for ___!",
    pick: 1,
  },
  { text: 'Coming soon! Batman vs. ___.', pick: 1 },
  { text: 'Class, pay close attention. I will now demonstrate the physics of ___.', pick: 1 },
  { text: "Hey Riley, I'll give you five bucks if you try ___.", pick: 1 },
  { text: 'Time to put on my favorite t-shirt, the one that says "I heart ___."', pick: 1 },
  { text: 'My dad and I enjoy ___ together.', pick: 1 },
  {
    text: "Hey, kids. I'm Sensei Todd. Today, I'm gonna teach you how to defend yourself against ___.",
    pick: 1,
  },
  { text: 'MY NAME CHUNGO.\\nCHUNGO LOVE ___.', pick: 1 },
  { text: 'Never fear, Captain ___ is here!', pick: 1 },
  { text: 'Kids, Dad is trying something new this week. It\'s called "___."', pick: 1 },
  { text: "Oh, no thank you, Mrs. Lee. I've had plenty of ___ for now.", pick: 1 },
  { text: "There's nothing better than a peanut butter and ___ sandwich.", pick: 1 },
  { text: 'And over here is Picasso\'s most famous painting, "Portrait of ___."', pick: 1 },
  { text: 'The aliens are here. They want ___.', pick: 1 },
  { text: 'They call me "Mr. ___."', pick: 1 },
  { text: 'CHUNGO FEEL SICK.\\nCHUNGO NO LIKE ___ ANYMORE.', pick: 1 },
  { text: "Mom!? You have to come pick me up! There's ___ at this party!", pick: 1 },
  { text: 'CNN breaking news! Over half of Americans are now ___.', pick: 1 },
  { text: 'On the next episode of Dora the Explorer, Dora explores ___.', pick: 1 },
  { text: 'Alright, which one of you little turds is responsible for ___?!', pick: 1 },
  {
    text: 'Ladies and gentlemen, I have discovered something amazing. I have discovered ___.',
    pick: 1,
  },
  {
    text: 'And in the blue corner, weighing in at 280 pounds, it\'s Tommy "___" Takahashi!',
    pick: 1,
  },
  { text: 'Outback Steakhouse: No rules. Just ___.', pick: 1 },
  { text: 'Ew. Grandpa smells like ___.', pick: 1 },
  {
    text: "My name is Peter Parker. I was bitten by a radioactive spider, and now I'm ___.",
    pick: 1,
  },
  { text: 'Put on your helmet, strap on your goggles, and get ready for ___!', pick: 1 },
  {
    text: 'Attention students! This is Principal Butthead reminding you that we do not allow ___ in the hallway. Thank you.',
    pick: 1,
  },
  { text: "What's about to take this school dance to the next level?", pick: 1 },
  { text: 'Little Miss Muffet Sat on a tuffet Eating her curds and ___.', pick: 1 },
  { text: 'All I want for Christmas is ___.', pick: 1 },
  { text: "Me and my friends don't play with dolls anymore. We're into ___ now.", pick: 1 },
  { text: "We're not supposed to go in the attic. My parents keep ___ in there.", pick: 1 },
  { text: "Police! Arrest this man! He's ___.", pick: 1 },
  { text: 'My favorite dinosaur is "___asaurus."', pick: 1 },
  { text: 'When I pooped, what came out of my butt?', pick: 1 },
  {
    text: "I'm not like the other children. Toys bore me, and I don't care for sweets. I prefer ___.",
    pick: 1,
  },
  { text: "I'm sorry, Mrs. Sanchez, but I couldn't finish my homework because of ___.", pick: 1 },
  { text: 'Oh Dark Lord, we show our devotion with a humble offering of ___!', pick: 1 },
  {
    text: 'Thanks for watching! If you want to see more vids of ___, smash that subscribe.',
    pick: 1,
  },
  { text: "We're off to see the wizard, the wonderful wizard of ___!", pick: 1 },
  { text: "What's all fun and games until somebody gets hurt?", pick: 1 },
  { text: 'Young lady, we do not allow ___ at the dinner table.', pick: 1 },
  { text: "Welcome! We're glad you're here. Now sit back, relax, and enjoy ___.", pick: 1 },
  { text: 'My favorite book is The Amazing Adventures of ___.', pick: 1 },
  { text: "Well, look what we have here! A big fancy man walkin' in like he's ___.", pick: 1 },
  { text: 'ENOUGH! I will not let ___ tear this family apart!', pick: 1 },
  { text: 'Rub a dub dub, ___ in a tub!', pick: 1 },
  { text: "Madam President, we've run out of time. The only option is ___.", pick: 1 },
  { text: 'I have invented a new sport. I call it "___ ball."', pick: 1 },
  { text: 'Hey, check out my band! We\'re called "Rage Against ___."', pick: 1 },
  { text: 'Moms love ___.', pick: 1 },
  { text: 'Where do babies come from?', pick: 1 },
  { text: 'CHUNGO ANGRY. CHUNGO DESTROY ___.', pick: 1 },
  { text: 'At school, I\'m just Mandy. But at summer camp, I\'m "___ Mandy."', pick: 1 },
  { text: 'James Bond will return in "No Time for ___."', pick: 1 },
  { text: "It's BIG. It's SCARY. It's ___!", pick: 1 },
  { text: 'Disney proudly presents: "___ on Ice."', pick: 1 },
  { text: 'What really killed the dinosaurs?', pick: 1 },
  { text: 'Beep beep! ___ coming through!', pick: 1 },
  { text: 'Now in bookstores: Nancy Drew and the Mystery of ___.', pick: 1 },
  { text: "You don't love me, Sam. All you care about is ___.", pick: 1 },
  { text: 'Did you know that Benjamin Franklin invented ___?', pick: 1 },
  { text: 'One nation, under God, indivisible, with liberty and ___ for all.', pick: 1 },
  {
    text: "The easiest way to tell me and my twin apart is that I have a freckle on my cheek and she's ___.",
    pick: 1,
  },
  {
    text: 'Hey guys. I just want to tell all my followers who are struggling with ___: it DOES get better.',
    pick: 1,
  },
  { text: 'Whoa there, partner! Looks like ___ spooked my horse.', pick: 1 },
  { text: 'Princess Marigold, the kingdom is in danger! You must stop ___.', pick: 1 },
  { text: "Shut up, Becky! At least I'm not ___.", pick: 1 },
  { text: 'I lost my arm in a ___ accident.', pick: 1 },
  { text: "Isn't this great, honey? Just you, me, the kids, and ___.", pick: 1 },
  { text: 'Foolish child! Did you think you could escape from ___?', pick: 1 },
  { text: 'Girls just wanna have ___.', pick: 1 },
  { text: "Run, run, as fast as you can. You can't catch me, I'm ___!", pick: 1 },
  { text: 'No fair! How come Chloe gets her own phone, and all I get is ___?', pick: 1 },
  { text: 'Bow before me, for I am the Queen of ___!', pick: 1 },
  { text: "New from Hasbro! It's BUNGO: The Game of ___.", pick: 1 },
  {
    text: "I don't really know what my mom's job is, but I think it has something to do with ___.",
    pick: 1,
  },
  { text: 'Our day at the water park was totally ruined by ___.', pick: 1 },
  { text: 'Charmander has evolved into ___!', pick: 1 },
  { text: 'What killed Old Jim?', pick: 1 },
  { text: 'Next from J.K. Rowling: Harry Potter and the Chamber of ___.', pick: 1 },
  { text: "What's keeping Dad so busy in the garage?", pick: 1 },
  { text: 'Boys? No. ___? Yes!', pick: 1 },
  { text: 'ME HUNGRY. ME WANT ___.', pick: 1 },
  { text: "Oh, that's my mom's friend Carl. He comes over and helps her with ___.", pick: 1 },
  { text: "Guys, stop it! There's nothing funny about ___.", pick: 1 },
  {
    text: "Huddle up, Wildcats! They may be bigger. They may be faster. But we've got a secret weapon: ___",
    pick: 1,
  },
  { text: 'I do not fight for wealth. I do not fight for glory. I fight for ___!', pick: 1 },
  { text: "Come on, Danny. All the cool kids are doin' it. Wanna try ___?", pick: 1 },
  { text: 'Coming to theaters this holiday season, "Star Wars: The Rise of ___."', pick: 1 },
  { text: "And today's soup is Cream of ___.", pick: 1 },
  { text: "Now in bookstores: 'The Audacity of ___,' by Barack Obama.", pick: 1 },
  { text: 'WHOOO! God damn I love ___!', pick: 1 },
  {
    text: 'Do you lack energy? Does it sometimes feel like the whole world is ___? Zoloft.®',
    pick: 1,
  },
  {
    text: "Hi, this is Jim from accounting. We noticed a $1,200 charge labeled '___.' Can you explain?",
    pick: 1,
  },
  { text: "Well if ___ is good enough for ___, it's good enough for me.", pick: 2 },
  { text: "Yo' mama so fat she ___!", pick: 1 },
  { text: 'What killed my boner?', pick: 1 },
  {
    text: 'Don\'t forget! Beginning this week, Casual Friday will officially become "___ Friday."',
    pick: 1,
  },
  {
    text: 'In his farewell address, George Washington famously warned Americans about the dangers of ___.',
    pick: 1,
  },
  { text: 'Having the worst day EVER. #___', pick: 1 },
  {
    text: "Get ready for the movie of the summer! One cop plays by the book. The other's only interested in one thing: ___.",
    pick: 1,
  },
  { text: "What's making things awkward in the sauna?", pick: 1 },
  {
    text: "Life's pretty tough in the fast lane. That's why I never leave the house without ___.",
    pick: 1,
  },
  { text: 'Patient presents with ___. Likely a result of ___.', pick: 2 },
  {
    text: "Hi MTV! My name is Kendra, I live in Malibu, I'm into ___, and I love to have a good time.",
    pick: 1,
  },
  { text: "Help me doctor, I've got ___ in my butt!", pick: 1 },
  { text: 'Why am I broke?', pick: 1 },
  { text: "I don't mean to brag, but they call me qthe Michael Jordan of ___.", pick: 1 },
  { text: 'Heed my voice, mortals! I am the god of ___, and I will not tolerate ___!', pick: 2 },
  {
    text: 'Here at the Academy for Gifted Children, we allow students to explore ___ at their own pace.',
    pick: 1,
  },
  {
    text: "Well what do you have to say for yourself, Casey? This is the third time you've been sent to the principal's office for ___.",
    pick: 1,
  },
  {
    text: 'In his new action comedy, Jackie Chan must fend off ninjas while also dealing with ___.',
    pick: 1,
  },
  {
    text: 'Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with ___: priceless.',
    pick: 1,
  },
  {
    text: 'Do the Dew ® with our most extreme flavor yet! Get ready for Mountain Dew ___!',
    pick: 1,
  },
  { text: 'My plan for world domination begins with ___.', pick: 1 },
  { text: 'The CIA now interrogates enemy agents by repeatedly subjecting them to ___.', pick: 1 },
  {
    text: 'Dear Sir or Madam, We regret to inform you that the Office of ___ has denied your request for ___',
    pick: 2,
  },
  {
    text: 'In Rome, there are whisperings that the Vatican has a secret room devoted to ___.',
    pick: 1,
  },
  { text: 'Science will never explain ___.', pick: 1 },
  { text: 'When all else fails, I can always masturbate to ___.', pick: 1 },
  { text: "I learned the hard way that you can't cheer up a grieving friend with ___.", pick: 1 },
  {
    text: 'In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ___.',
    pick: 1,
  },
  { text: 'An international tribunal has found ___ guilty of ___.', pick: 2 },
  {
    text: 'The socialist governments of Scandinavia have declared that access to ___ is a basic human right.',
    pick: 1,
  },
  { text: 'In his new self-produced album, Kanye West raps over the sounds of ___.', pick: 1 },
  { text: "What's the gift that keeps on giving?", pick: 1 },
  {
    text: 'Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ___ and his wits.',
    pick: 1,
  },
  {
    text: "In the distant future, historians will agree that ___ marked the beginning of America's decline.",
    pick: 1,
  },
  { text: 'In a pinch, ___ can be a suitable substitute for ___.', pick: 2 },
  { text: 'What has been making life difficult at the nudist colony?', pick: 1 },
  { text: "Michael Bay's new three-hour action epic pits ___ against ___.", pick: 2 },
  { text: "And I would have gotten away with it, too, if it hadn't been for ___.", pick: 1 },
  { text: 'What brought the orgy to a grinding halt?', pick: 1 },
  {
    text: "2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she's looking for ___.",
    pick: 1,
  },
  { text: 'Adventure. Romance. ___. From Paramount Pictures, "___."', pick: 2 },
  {
    text: 'Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation ___.',
    pick: 1,
  },
  { text: 'As king, how will I keep the peasants in line?', pick: 1 },
  {
    text: 'Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of ___.',
    pick: 1,
  },
  { text: 'Do not fuck with me! I am literally ___ right now.', pick: 1 },
  { text: 'Every step towards ___ gets me a little bit closer to ___.', pick: 2 },
  {
    text: "Forget everything you know about ___, because now we've supercharged it with ___!",
    pick: 2,
  },
  {
    text: "Honey, I have a new role-play I want to try tonight! You can be ___, and I'll be ___.",
    pick: 2,
  },
  { text: 'How am I compensating for my tiny penis?', pick: 1 },
  { text: 'I am become ___, destroyer of ___!', pick: 2 },
  {
    text: "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by ___.",
    pick: 1,
  },
  { text: "I'm sorry sir, but we don't allow ___ at the country club.", pick: 1 },
  { text: "If you can't handle ___, you'd better stay away from ___.", pick: 2 },
  { text: 'In return for my soul, the Devil promised me ___ but all I got was ___.', pick: 2 },
  { text: 'In the beginning there was ___. And the Lord said, "Let there be ___."', pick: 2 },
  {
    text: 'It lurks in the night. It hungers for flesh. This summer, no one is safe from ___.',
    pick: 1,
  },
  { text: 'Man, this is bullshit. Fuck ___.', pick: 1 },
  { text: 'Oprah\'s book of the month is "___ For ___: A Story of Hope"', pick: 2 },
  { text: "She's up all night for good fun. I'm up all night for ___.", pick: 1 },
  { text: 'The Japanese have developed a smaller, more efficient version of ___.', pick: 1 },
  { text: "This is the prime of my life. I'm young, hot, and full of ___.", pick: 1 },
  { text: 'This year\'s hottest album is "___" by ___.', pick: 2 },
  { text: 'We never did find ___, but along the way we sure learned a lot about ___.', pick: 2 },
  {
    text: "Wes Anderson's new film tells the story of a precocious child coming to terms with ___.",
    pick: 1,
  },
  { text: "What's fun until it gets weird?", pick: 1 },
  {
    text: "You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon ___!",
    pick: 1,
  },
  { text: '___ may pass, but ___ will last forever.', pick: 2 },
  { text: '___ will never be the same after ___.', pick: 2 },
  {
    text: "You guys, I saw this crazy movie last night. It opens on ___, and then there's some stuff about ___, and then it ends with ___.",
    pick: 3,
  },
  { text: 'During his midlife crisis, my dad got really into ___.', pick: 1 },
  { text: '___ would be woefully incomplete without ___.', pick: 2 },
  { text: 'My new favorite porn star is Joey "___" McGee.', pick: 1 },
  {
    text: 'Before I run for president, I must destroy all evidence of my involvement with ___.',
    pick: 1,
  },
  { text: 'This is your captain speaking. Fasten your seatbelts and prepare for ___.', pick: 1 },
  { text: 'In his newest and most difficult stunt, David Blaine must escape from ___.', pick: 1 },
  { text: 'The Five Stages of Grief: denial, anger, bargaining, ___, and acceptance.', pick: 1 },
  {
    text: 'My mom freaked out when she looked at my browser history and found ___.com/___.',
    pick: 2,
  },
  { text: 'I went from ___ to ___, all thanks to ___.', pick: 3 },
  {
    text: "Members of New York's social elite are paying thousands of dollars just to experience ___.",
    pick: 1,
  },
  {
    text: 'This month\'s Cosmo: "Spice up your sex life by bringing ___ into the bedroom."',
    pick: 1,
  },
  { text: 'Little Miss Muffet Sat on a tuffet, Eating her curds and ___.', pick: 1 },
  { text: "If God didn't want us to enjoy ___, he wouldn't have given us ___.", pick: 2 },
  { text: "My country, 'tis of thee, sweet land of ___.", pick: 1 },
  {
    text: 'After months of debate, the Occupy Wall Street General Assembly could only agree on "More ___!"',
    pick: 1,
  },
  { text: 'I spent my whole life working toward ___, only to have it ruined by ___.', pick: 2 },
  { text: 'Next time on Dr. Phil: How to talk to your child about ___.', pick: 1 },
  { text: 'Only two things in life are certain: death and ___.', pick: 1 },
  {
    text: "Everyone down on the ground! We don't want to hurt anyone. We're just here for ___.",
    pick: 1,
  },
  { text: 'The healing process began when I joined a support group for victims of ___.', pick: 1 },
  { text: 'The votes are in, and the new high school mascot is ___.', pick: 1 },
  { text: 'Charades was ruined for me forever when my mom had to act out ___.', pick: 1 },
  { text: 'Before ___, all we had was ___.', pick: 2 },
  { text: "Tonight on 20/20: What you don't know about ___ could kill you.", pick: 1 },
  {
    text: "You haven't truly lived until you've experienced ___ and ___ at the same time.",
    pick: 2,
  },
  {
    text: 'I work my ass off all day for this family, and this is what I come home to? ___!?',
    pick: 1,
  },
  {
    text: 'I have a strict policy. First date, dinner. Second date, kiss. Third date, ___.',
    pick: 1,
  },
  { text: 'When I was a kid, we used to play Cowboys and ___.', pick: 1 },
  {
    text: "This is America. If you don't work hard, you don't succeed. I don't care if you're black, white, purple, or ___.",
    pick: 1,
  },
  { text: "You Won't Believe These 15 Hilarious ___ Bloopers!", pick: 1 },
  {
    text: 'James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: ___.',
    pick: 1,
  },
  { text: "Don't worry kid. It gets better. I've been living with ___ for 20 years.", pick: 1 },
  {
    text: 'My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and ___.',
    pick: 1,
  },
  { text: 'Behind every powerful man is ___.', pick: 1 },
  { text: 'You are not alone. Millions of Americans struggle with ___ every day.', pick: 1 },
  {
    text: 'Come to Dubai, where you can relax in our world famous spas, experience the nightlife, or simply enjoy ___ by the poolside.',
    pick: 1,
  },
  { text: '"This is madness." "No, THIS IS ___!"', pick: 1 },
  {
    text: "Listen Gary, I like you. But if you want that corner office, you're going to have to show me ___.",
    pick: 1,
  },
  {
    text: 'I went to the desert and ate of the peyote cactus. Turns out my spirit animal is ___.',
    pick: 1,
  },
  { text: 'And would you like those buffalo wings mild, hot, or ___?', pick: 1 },
  {
    text: 'The six things I could never do without: oxygen, Facebook, chocolate, Netflix, friends, and ___ LOL!',
    pick: 1,
  },
  { text: "Why won't you make love to me anymore? Is it ___?", pick: 1 },
  {
    text: 'Puberty is a time of change. You might notice hair growing in new places. You might develop an interest in ___. This is normal.',
    pick: 1,
  },
  {
    text: "I'm sorry, Mrs. Chen, but there was nothing we could do. At 4:15 this morning, your son succumbed to ___.",
    pick: 1,
  },
  {
    text: "I'm Miss Tennessee, and if I could make the world better by changing one thing, I would get rid of ___.",
    pick: 1,
  },
  {
    text: "Tonight we will have sex. And afterwards, If you'd like, a little bit of ___.",
    pick: 1,
  },
  {
    text: "Everybody join hands and close your eyes. Do you sense that? That's the presence of ___ in this room.",
    pick: 1,
  },
  {
    text: 'To become a true Yanomamo warrior, you must prove that you can withstand ___ without crying out.',
    pick: 1,
  },
  {
    text: "Y'all ready to get this thing started? I'm Nick Cannon, and this is America's Got ___.",
    pick: 1,
  },
  {
    text: 'If you had to describe the Card Czar, using only one of the cards in your hand, which one would it be?',
    pick: 1,
  },
  { text: 'A successful job interview begins with a firm handshake and ends with ___.', pick: 1 },
  { text: "Lovin' you is easy 'cause you're ___.", pick: 1 },
  { text: 'My life is ruled by a vicious cycle of ___ and ___.', pick: 2 },
  {
    text: 'The blind date was going horribly until we discovered our shared interest in ___.',
    pick: 1,
  },
  { text: '___. Awesome in theory, kind of a mess in practice.', pick: 1 },
  { text: "I'm not like the rest of you. I'm too rich and busy for ___.", pick: 1 },
  { text: 'In the seventh circle of Hell, sinners must endure ___ for all eternity.', pick: 1 },
  { text: '___: Hours of fun. Easy to use. Perfect for ___!', pick: 2 },
  { text: 'What left this stain on my couch?', pick: 1 },
  {
    text: 'Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ___ in the workplace.',
    pick: 1,
  },
  { text: 'When you get right down to it, ___ is just ___.', pick: 2 },
  { text: 'Turns out that ___-Man was neither the hero we needed nor wanted.', pick: 1 },
  { text: 'As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ___.', pick: 1 },
  { text: "Money can't buy me love, but it can buy me ___.", pick: 1 },
  { text: 'With enough time and pressure, ___ will turn into ___.', pick: 2 },
  { text: 'And what did you bring for show and tell?', pick: 1 },
  { text: 'During high school, I never really fit in until I found ___ club.', pick: 1 },
  { text: "Hey, baby, come back to my place and I'll show you ___.", pick: 1 },
  { text: "After months of practice with ___, I think I'm finally ready for ___.", pick: 2 },
  {
    text: 'To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ___.',
    pick: 1,
  },
  { text: 'Finally! A service that delivers ___ right to your door.', pick: 1 },
  { text: 'My gym teacher got fired for adding ___ to the obstacle course.', pick: 1 },
  { text: 'Having problems with ___? Try ___!', pick: 2 },
  {
    text: "As part of his contract, Prince won't perform without ___ in his dressing room.",
    pick: 1,
  },
  {
    text: "Listen, son. If you want to get involved with ___, I won't stop you. Just steer clear of ___.",
    pick: 2,
  },
]

export const WHITE_CARDS: string[] = [
  "Sucking the President's dick",
  'Sunny D! Alright!',
  'A mulatoo, an albino, a mosquito, and my libido',
  'Log™',
  'Jerking off to a 10-second RealMedia clip',
  'Deregulating the mortgage market',
  'The Y2K bug',
  "Wearing Nicolas Cage's face",
  'Stabbing the shit out a Capri Sun',
  "Kurt Cobain's death",
  'Freeing Willy',
  'Liking big butts and not being able to lie about it',
  'The Great Cornholio',
  'Pure Moods, Vol. 1',
  "Yelling 'girl power!' and doing a high kick",
  "Pamela Anderson's boobs running in slow motion",
  'Pizza in the morning, pizza in the evening, pizza at supper time',
  'Angels interfering in an otherwise fair baseball game',
  'Getting caught up in the CROSSFIRE™',
  'Patti Mayonnaise',
  'Cool 90s up-in-the-front hair',
  'Several Michael Keatons',
  'A bus that will explode if it goes under 50 miles per hour',
  'Silence',
  'The illusion of choice in a late-stage capitalist society',
  'Many bats',
  'Famine',
  'Flesh-eating bacteria',
  'Flying sex snakes',
  'Not giving a shit about the Third World',
  'Magnets',
  'Shapeshifters',
  'Seeing what happens when you lock people in a room with hungry seagulls',
  'A crucifixion',
  'Jennifer Lawrence',
  '72 virgins',
  'A live studio audience',
  'A time travel paradox',
  'Authentic Mexican cuisine',
  'Doing crimes',
  'Synergistic management solutions',
  'Crippling debt',
  'Daddy issues',
  'Used panties',
  'A fart so powerful that it wakes the giants from their thousand-year slumber',
  'Former President George W. Bush',
  'Full frontal nudity',
  'Soft, kissy missionary sex',
  'BATMAN',
  'Agriculture',
  'Barely making $25,000 a year',
  'Covering myself with Parmesan cheese and chili flakes because I am pizza',
  'Laying an egg',
  'Getting naked and watching Nickelodeon.',
  'Pretending to care',
  'Natural selection',
  'Coat hanger abortions',
  'Sex with Patrick Stewart',
  "My abusive boyfriend who really isn't so bad once you get to know him",
  'Having big dreams but no realistic way to achieve them',
  'Seeing Grandma naked',
  'Boogers',
  'The inevitable heat death of the universe',
  'Prescription pain killers',
  'Swooping',
  'Mansplaining',
  'A homoerotic volleyball montage',
  'The miracle of child birth',
  'The Rapture',
  'Whipping it out',
  'White privilege',
  'Alexandria Ocasio-Cortez',
  'Putting things where they go',
  'Fragile masculinity',
  'All-you-can-eat shrimp for $8.99',
  'Emerging from the sea and rampaging through Tokyo',
  'The Hamburglar',
  'AXE Body Spray',
  'The Blood of Christ',
  "An old guy who's almost dead",
  'Kanye West',
  'Hot cheese',
  'Raptor attacks',
  'Seven dead and three in critical condition',
  'Smegma',
  'Alcoholism',
  'A middle-aged man on rollerskates',
  'The past',
  'My genitals',
  'An endless stream of diarrhea',
  'Science',
  'Looking in the mirror, applying lipstick, and whispering "tonight, you will have sex with Tom Cruise"',
  'Bingeing and purging',
  'An oversized lollipop',
  'Self-loathing',
  'Not reciprocating oral sex',
  'Flightless birds',
  'A good sniff',
  '50,000 volts straight to the nipples',
  "Sitting on my face and telling me I'm garbage",
  'Half-assed foreplay',
  'The Holy Bible',
  'German dungeon porn',
  'A balanced breakfast',
  'Dead birds everywhere',
  'The arrival of the pizza',
  'Permanent Orgasm-Face Disorder',
  'Being on fire',
  'Teenage pregnancy',
  'Gandhi',
  'Your weird brother',
  'The cool, refreshing taste of Pepsi®',
  'Chemical weapons',
  'Oprah',
  "Wondering if it's possible to get some of that salsa to go",
  'A Fleshlight®',
  'A pyramid of severed heads',
  'An erection that lasts longer than four hours',
  "A three-way with my wife and Shaquille O'Neal",
  'Bananas',
  'Passive aggressive Post-it notes',
  "Hillary Clinton's emails",
  'Switching to Geico®',
  'Peeing a little bit',
  'Wet dreams',
  'The Jews',
  'My cheating son-of-a-bitch husband',
  'Poverty',
  'Kamikaze pilots',
  'Committing suicide',
  'The homosexual agenda',
  'Powerful thighs',
  'These hoes',
  'The only gay person in a hundred miles',
  'Having sex for the first time',
  'A Mexican',
  'A falcon with a cap on its head',
  'Wizard music',
  'The Kool-Aid Man',
  'Donald J. Trump',
  'Kissing grandma on the forehead and turning off her life support',
  'Sexual tension',
  'An AR-15 assault rifle',
  'Juuling',
  'Free samples',
  'Hurting those closest to me',
  'Doing the right thing',
  'My good bra',
  'Punching a congress man in the face',
  'Fancy Feast®',
  'Being rich',
  'The Three-Fifths Compromise',
  'Lactation',
  'World peace',
  'Shutting up so I can watch the game',
  'Sweet, sweet vengeance',
  'Republicans',
  'Sniffing and kissing my feet',
  'A much younger woman',
  "Eating a hard boiled egg out of my husband's asshole",
  'RoboCop',
  'One titty hanging out',
  'Justin Bieber',
  'Oompa-Loompas',
  'Inappropriate yodeling',
  'Puberty',
  'Ghosts',
  'Expecting a burp and vomiting on the floor',
  'Adderall®',
  'The Red Hot Chili Peppers',
  'Sideboob',
  '50 mg of Zoloft daily',
  'Fucking my sister',
  'Braiding three penises into a Twizzler',
  'Vigorous jazz hands',
  'An octopus giving seven handjobs and smoking a cigarette',
  'My neck, my back, my pussy, and my crack',
  'J. D. Power and his associates',
  'Mouth herpes',
  'Getting fingered',
  'My Uber driver, Pavel',
  'GoGurt®',
  'Police brutality',
  'Sperm whales',
  'Women of color',
  'Men discussing their feelings in an emotionally healthy way',
  'Incest',
  'Filling my briefcase with business stuff',
  'Preteens',
  'My fat daughter',
  'Rap music',
  'Pac-Man uncontrollably guzzling cum',
  'Casually suggesting a threesome',
  'Running out of semen',
  'God',
  'Fading away into nothingness',
  'Darth Vader',
  'A sad handjob',
  "Exactly what you'd expect",
  'The wonders of the Orient',
  'Sexual peeing',
  'Emotions',
  'Licking things to claim them as your own',
  'Jobs',
  'The placenta',
  'Spontaneous human combustion',
  'The Bachelorette season finale',
  'A tiny horse',
  'William Shatner',
  'Selling crack to children',
  'An M. Night Shyamalan plot twist',
  'Throwing grapes at a man until he loses touch with reality',
  'Establishing dominance',
  'Finger painting',
  'Old-people smell',
  'Brown people',
  'Mutually assured destruction',
  'Pedophiles',
  'Yeast',
  'Getting crushed by a vending machine',
  'My inner demons',
  'A Super Soaker™ full of cat pee',
  'Aaron Burr',
  'How bad my daughter fucked up her dance recital',
  'Rectangles',
  'Catapults',
  'Poor people',
  'Cuddling',
  'However much weed $20 can buy',
  'Battlefield amputations',
  'Spaghetti? Again?',
  'Only dating Asian women',
  'The Hustle',
  'The Force',
  'How amazing it is to be on mushrooms',
  'Ronald Reagan',
  'A disappointing birthday party',
  'Nachos for the table',
  'Becoming a blueberry',
  'Judging everyone',
  'Kourtney, Kim, Khloe, Kendall, and Kylie',
  'Getting married, having a few kids, buying some stuff, retiring to Florida, and dying',
  'Some god damn peace and quiet',
  'AIDS',
  'Pictures of boobs',
  'Strong female characters',
  'Some foundation, mascara, and a touch of blush',
  'Getting cummed on',
  'Pixelated bukkake',
  'A lifetime of sadness',
  'Going an entire day without masturbating',
  'Hospice care',
  'Getting really high',
  'The opiod epidemic',
  'Penis envy',
  'Dick pics',
  'Racism',
  'Menstrual rage',
  'Sunshine and rainbows',
  'Gay conversion therapy',
  'Ruth Bader Ginsburg brutally gaveling your penis',
  'German Chancellor Angela Merkel',
  'The KKK',
  'Radical Islamic terrorism',
  'Huge biceps',
  'My little boner',
  'Dry heaving',
  'A pangender octopus who roams the cosmos insearch of love',
  'Meth',
  'Serfdom',
  'Holding down a child and farting all over him',
  'A gossamer stream of jizz that catches the light as it arcs through the morning air',
  'Executing a hostage every hour',
  'The rhythms of Africa',
  'Breaking out into song and dance',
  'A Bop It™',
  'A whole thing of butter',
  'Still being a virgin',
  'Solving problems with violence',
  'Leprosy',
  'Gloryholes',
  'Nipple blades',
  'The heart of a child',
  'Puppies!',
  'Fellowship in Christ',
  'Little boy penises',
  "Waking up half-naked in a Denny's parking lot",
  'The Pope',
  'White people',
  'Tentacle porn',
  'My bright pink fuckhole',
  'An older woman who knows her way around the penis',
  'Getting drugs off the street and into my body',
  "Daniel Radcliffe's delicious asshole",
  'Active listening',
  'How far I can get my own penis up my butt',
  'Having anuses for eyes',
  'The penny whistle solo from "MyHeart Will Go On"',
  'Seppuku',
  'Ethnic cleansing',
  'Itchy pussy',
  'Blowing my boyfriend so hard he shits',
  'A fuck-ton of almonds',
  'Danny DeVito',
  'The magic of live theatre',
  'Throwing a virgin into a volcano',
  'Dwayne "The Rock" Johnson',
  "A salad for men that's made of metal",
  'Waiting till marriage',
  'Unfathomable stupidity',
  'Shiny objects',
  'Accepting the way things are',
  'NBA superstar LeBron James',
  'Listening to her problems without trying to solve them',
  'Therapy',
  'The Devil himself',
  'Autocannibalism',
  'Erectile dysfunction',
  'My collection of Japanese sex toys',
  'Being fat and stupid',
  'Pooping back and forth',
  'Forever',
  'Tearing that ass up like wrapping paper on Christmas morning',
  'More elephant cock than I bargained for',
  'A salty surprise',
  'The South',
  'The violation of our most basic human rights',
  "Tap dancing like there's no tomorrow",
  'A bowl of mayonnaise and human teeth',
  'Fiery poops',
  'Saying "I love you"',
  'Inserting a Mason jar into my anus',
  'Consensual sex',
  'Telling a shitty story that goes nowhere',
  'A good, strong gorilla',
  'Seeing my father cry',
  'The true meaning of Christmas',
  'Some of the best rappers in the game',
  "Owning and operating a Chili's franchise",
  'Estrogen',
  'Necrophilia',
  'Being a woman',
  'Getting into a pretty bad car accident',
  'Bill Nye the Science Guy',
  'Girls',
  'The Russians',
  'A bleached asshole',
  'Fucking the weatherman on live television',
  'Black people',
  'The Boy Scouts of America',
  'Lunchables™',
  'Bitches',
  'PTSD',
  'Dark and mysterious forces beyond our control',
  'Smallpox blankets',
  'Masturbating',
  'Some punk kid who stole my turkey sandwich',
  'Heartwarming orphans',
  'Spirit Airlines',
  'Bubble butt bottom boys',
  'Hobos',
  'Queefing',
  'The guys from Queer Eye',
  'Cardi B',
  'Viagra®',
  'Soup that is too hot',
  'Muhammad (Peace Be Upon Him)',
  'Explaining how vaginas work',
  "Doin' it in the butt",
  'My ex-wife',
  'Teaching a robot to love',
  'Touching a pug right on his penis',
  'Academy Award winner Meryl Streep',
  'Drinking alone',
  'Dick fingers',
  'Multiple stab wounds',
  'A windmill full of corpses',
  'Count Chocula',
  'Vladimir Putin',
  'The Patriarchy',
  'Poopy diapers',
  'Child abuse',
  'Anal beads',
  'Slaughtering innocent civilians',
  'The glass ceiling',
  'Vomiting seafood and bleeding anally',
  'The American Dream',
  'Not wearing pants',
  'Pulling out',
  'Being able to talk to elephants',
  'Horse meat',
  'A really cool hat',
  'My balls on your face',
  'Pooping in a laptop and closing it',
  'Dead babies',
  'Foreskin',
  'Stalin',
  'A stray pube',
  'Worshipping that pussy',
  'Completely unwarranted confidence',
  'A saxophone solo',
  'Italians',
  'A fetus',
  'Firing a rifle in to the air while balls deep in a squealing hog',
  'Mike Pence',
  '10,000 Syrian refugees',
  'Forced sterilization',
  'My relationship status',
  'Nicolas Cage',
  'Child beauty pageants',
  'Explosions',
  'Not vaccinating my children because I am stupid',
  'An unwanted pregnancy',
  'Diversity',
  'A white ethno state',
  'Bees?',
  'Lena Dunham',
  'Huffing spray paint',
  'A man on the brink of orgasm',
  'Repression',
  'Harry Potter erotica',
  'Giving birth to the Antichrist',
  'Three dicks at the same time',
  'Nazis',
  'Invading Poland',
  'My vagina',
  'Assless chaps',
  'Murder',
  '8 oz of sweet Mexican black-tar heroin',
  'What that mouth do',
  'Dead parents',
  'Object permanence',
  'Giving 110%',
  'Her Majesty, Queen Elizabeth II',
  'The Trail of Tears',
  'Memes',
  'Opposable thumbs',
  'Racially-biased SAT questions',
  'The Great Depression',
  'Chainsaws for hands',
  'Sex with animals',
  'Being marginalized',
  'Goblins',
  'Hope',
  'Liberals',
  'A micropenis',
  'My soul',
  'A ball of earwax, semen, and toenail clippings',
  'Illegal immigrants',
  'Elderly Japanese men',
  'The female orgasm',
  'Hetero normativity',
  'A horde of Vikings',
  'Hot people',
  'Seething with quiet resentment',
  'An Oedipus complex',
  'Crumbs all over the god damn carpet',
  'Arnold Schwarzenegger',
  'The wifi password',
  'Spectacular abs',
  'Geese',
  'Extremely tight pants',
  'Fox News',
  "A little boy who won't shut the fuck up about dinosaurs",
  'A bird that shits human turds',
  'A mopey zoo lion',
  'A bag of magic beans',
  'Poor life choices',
  'Making a pouty face',
  'Vehicular mans laughter',
  "Women's suffrage",
  'Some guy',
  'My sex life',
  'Auschwitz',
  'A snapping turtle biting the tip of your penis',
  "All the dudes I've fucked",
  'Judge Judy',
  'African children',
  "This month's mass shooting",
  'Barack Obama',
  'The clitoris',
  'The Big Bang',
  'Land mines',
  'The entire Mormon Tabernacle Choir',
  'A micro pig wearing a tiny rain coat and booties',
  'Penis breath',
  "Jerking off into a pool of children's tears",
  'Man meat',
  'Farting and walking away',
  'Being a dick to children',
  'One trillion dollars',
  'Drowning the kids in the bathtub',
  'Me time',
  'The Underground Railroad',
  'Poorly-timed Holocaust jokes',
  'A sea of troubles',
  'Dying',
  'Drinking out of the toilet and eating garbage',
  'The gays',
  'The screams',
  'The terrible screams',
  'Lumberjack fantasies',
  "Morgan Freeman's voice",
  'Women in yogurt commercials',
  'Natural male enhancement',
  'Men',
  'The bombing of Nagasaki',
  'Fake tits',
  'The Amish',
  'Being a mother fucking sorcerer',
  'My black ass',
  'Genuine human connection',
  'Announcing that I am about to cum',
  'David Bowie flying in on a tiger made of lightning',
  'My ugly face and bad personality',
  'A bitch slap',
  'A brain tumor',
  'Balls',
  'Grandma',
  'Friction',
  'Chunks of dead hitchhiker',
  'Fear itself',
  'Jews, gypsies, and homosexuals',
  'The milkman',
  'Cards Against Humanity',
  'The biggest, blackest dick',
  'A box',
  'A box within a box',
  'A boxing match with a giant box',
  'A box of biscuits, a box of mixed biscuits, and a biscuit mixer',
  'An outbreak of smallbox',
  'The Boxcar Children',
  'A world without boxes',
  'Boxing up my feelings',
  'A box-shaped man',
  'A man-shaped box',
  'Something that looks like a box but turns out to be a crate',
  "A box that is conscious and wishes it weren't a box",
  'An alternate universe in which boxes store things inside of people',
  'The J15 Patriot Assault Box',
  'A box without hinges, key, or lid, yet golden treasure inside is hid',
  'Two midgets shitting into a box',
  'A falcon with a box on its head',
  'Being a motherfucking box',
  'Former President George W Box',
  "Pandora's vagina",
  'Snotsicles',
  'Naked News',
  "Done Cherry's wardrobe",
  'Syrupy sex with a maple tree',
  "Terry Fox's prosthetic leg",
  "Canada: American's hat",
  'Homo milk',
  'Mr. Dressup',
  'The Front de Libération du Québec',
  'Heritage minutes',
  'The Royal Canadian Mounted Police',
  'Stephen Harper',
  'Burning down the White House',
  'Being Canadian',
  'The Famous Five',
  'A Molson muscle',
  'An icy hand job from an Edmonton hooker',
  'Poutine',
  'Schmirler the Curler',
  'The Official Languages Act. La Loi sure les langues officielles',
  'Newfies',
  'The CBC',
  'Graham Greene playing the same First Nations character on every TV show',
  'Killing a moose with your bare hands',
  'tim Hortons',
  'Quintland',
  'Karla Momolka',
  'A big wet kiss from Great Aunt Sharon.',
  'A cloud that rains diarrhea',
  'A pirate with two peg arms, two peg legs, and a peg head',
  'Athena, Goddess of Wisdom',
  'Baby boomers',
  'Beautiful Grandma',
  "Defecating on the neighbor's lawn",
  'Eight hours of video games',
  'Going night-night',
  'Hanging out with Zendaya',
  'Kissing Mom on the lips',
  'Me, your dad',
  'Playing trumpet for the Mayor',
  'Ratzilla',
  'Teeny tiny turds',
  'That there tarantula',
  'The way Grandpa smells',
  'Three glasses of red wine',
  'Whatever Dad does at work',
  'Getting shot out of a cannon',
  'Jesus',
  'Eating pasta out of my pants',
  'A burrito smoothie',
  'A bear',
  'Old people',
  "My sister's stupid boyfriend",
  'Stuffing my underwear with pancakes',
  'Stinky Martha, the superhero that nobody likes',
  'My chainsaw',
  'Diarrhea',
  'The police',
  "Sniffing a dog's butt",
  'Horrible allergies',
  'Your face',
  'A gerbil named "Gerbil"',
  'Fartus Magnimus, God of Beans',
  'Rated-R stuff',
  'Blowing up the Moon',
  'Getting launched into space',
  'Likes',
  "A bird pooping on the president's head",
  'Chungo, the talking gorilla',
  'The way I feel when I see Kyle',
  'Hot gossip',
  'Forgetting to put on underwear',
  'Running full speed into a wall',
  'A black hole',
  'Putting my butt on stuff',
  'Racism, sexism, and homophobia',
  'Making the bees angry',
  'My strong, terrifying daughter',
  'A Democrat',
  'TikTok',
  'Cheeto fingers',
  "A huge honkin' carrot",
  'The country of Bolivia',
  'My parents',
  'Idiots',
  'Filling my butt with spaghetti',
  "Putting an apple in a little boy's mouth and roasting him for dinner",
  'Thousands of lasagna',
  "Climbing into a cow's butt",
  'War with Canada',
  'Mashing a banana into your belly button',
  'China',
  'Shrek',
  'Cavities',
  'Eating people',
  'Butts of all shapes and sizes',
  'A 40-piece Chicken McNuggets',
  'Climate change',
  'Barf',
  'A poop as big as Mom',
  'A couch that eats children',
  'Going to Hell',
  'The loose skin at the joint of the elbow known as "the weenus"',
  'A horse with no legs',
  'Fat stacks of cash',
  'Dora the Explorer',
  'Illegal drugs',
  'BULBASAUR',
  "Dad's meatloaf",
  'Extra-warm Pepsi',
  'The old man with the rake who lives down the dark and winding road',
  'Calling 9-1-1',
  "Spending my parents' hard-earned money",
  'Toe jam',
  'Hot lava',
  'Butt surgery',
  'Freeing all the animals from the zoo',
  'A bountiful harvest of squashes and corns',
  'Bombs',
  'Boobies',
  'Respecting personal boundaries',
  "Having no idea what's going on",
  'John Wilkes Booth',
  'Getting married',
  'Politics',
  'Garbage',
  'Naked people',
  'This stupid game',
  'Biting a rich person',
  'Screaming at birds',
  'Getting stuck in the toilet',
  'Getting crushed by a piano',
  'Huge pants',
  "Mom's spaghetti",
  'An old, dirty cat with bad breath',
  'A corn dog',
  'My followers',
  'Principal Butthead',
  'A statue of a naked guy',
  'A tiny detective who solves tiny crimes',
  'Joining the army',
  'Witchcraft',
  'Taking out my eyeballs',
  'Sacrificing Uncle Tim',
  'Moving to Ohio',
  'A hundred screaming monkeys',
  'A wise old woman with no teeth and cloudy eyes',
  'Ham',
  'Clams',
  'Spider-Man',
  'Trying to catch that dang raccoon',
  'Slapping my huge belly',
  'The doll that watches me sleep',
  'Money',
  'LeBron James',
  "Father's forbidden chocolates",
  'Me',
  'Salmon',
  'Screaming the F-word',
  'A whole thing of cottage cheese',
  'Crab-walking from the toilet to get more toilet paper',
  'Mayonnaise',
  'Total world domination',
  'Failure',
  'JoJo Siwa',
  'Getting kicked in the nuts',
  'Sharks with legs',
  'Triangles',
  'Ninjas',
  'The floor',
  'The whole family',
  'Bench pressing a horse',
  'Spiders',
  'Uranus',
  'A Republican',
  'Giving wedgies to my haters',
  '14 cheeseburgers, 6 large fries, and a medium Sprite',
  'Big Randy',
  'Blasting my math teacher into the sun',
  'Dreaming about boys',
  'Taking a dump in the pool',
  'Crying in the bathroom',
  'Happiness',
  'Poison',
  "My sister's hair all over the place",
  'A scoop of tuna',
  'Doing karate',
  'Hades, God of the Underworld',
  'Lil Nas X',
  "Dad's famous poops",
  'Squirty cheese',
  'My girlfriend, who goes to another school',
  'Mowing the stupid lawn',
  'Slapping that butt',
  'Questioning authority',
  'Chugging a gallon of milk and then vomiting a gallon of milk',
  'Farting a lot today',
  'Going bald',
  'Germs',
  'Nuclear war',
  'Barfing into a popcorn bucket',
  'A cursed llama with no eyes',
  'The wettest fart you ever heard',
  "Shaving Dad's back",
  'Overthrowing the government',
  'Murdering',
  'Exploding',
  'Bleeding',
  'The oppressive system of capitalism',
  'Supreme Court Justice Ruth Bader Ginsburg',
  'A long, hot pee',
  'Throwing up double peace signs with my besties at Starbucks',
  'A balloon filled with chili',
  'The dishes',
  'The freedom of speech',
  'Egg salad',
  "Mom's friend, Donna",
  'Rich people',
  'Pirate music',
  'Being a dinosaur',
  'A fake kid made out of wood',
  'Homework',
  'Batman',
  'A dead body',
  'Drinking a whole bottle of ranch',
  'Destroying the planet',
  'Living in a pineapple under the sea',
  'Pizza',
  'This pumpkin',
  'Extremely tight underpants',
  'A nice, warm glass of pee',
  'Poseidon, Lord of the Sea',
  'Complaining',
  'Bursting into flames',
  'Spawning sheep',
  'My whole body getting big and strong and beautiful',
  'Big, juicy pimples',
  'The humble earthworm',
  'The garbage man',
  'A big, and I mean BIG turtle',
  'Your mom!',
  'The octopus stuck to my face',
  'Dying of old age',
  'Smashing the patriarchy',
  'Screaming into a can of Pringles',
  'Grandpa',
  'Shutting up',
  'My annoying brother',
  'My future husband',
  'A hot air balloon powered by fart gas',
  'Sitting on the toilet and going poop',
  'A screaming soccer dad',
  'Cocktail weenies',
  'The British',
  'Voldemort',
  'Picking my nose and eating it',
  'Having a really big head',
  'A dead whale',
  'Fortnite',
  'The power of the Dark Side',
  'Big butt cheeks filled with poop',
  'My friend Steve',
  'Violence',
  'Magic: The Gathering',
  'Eating toenail clippings',
  'Using balloons as boobies',
  'My dang kids',
  'Squeezing a lemon into my eye',
  'Tombus, the talking rhombus',
  'Greta Thunberg',
  'Ellen',
  'Uncle Bob',
  'Outback Steakhouse',
  'A baby with a full mustache',
  'Getting hit in the face with a soccer ball',
  'Eating a whole roll of toilet paper',
  'The bacon',
  'The first female president of the United States',
  'Falling off a mountain',
  'Person milk',
  'Pink eye',
  'Pork',
  'The government',
  'Nunchucks',
  'Nothing',
  'GOOOAAALLLL!!!',
  "Mom's new haircut",
  'Happy daddies with happy sandals',
  'Giggling and farting and slurping milkshakes',
  'Ice pee',
  'Obama',
  'Twerking',
  "Reading my sister's diary",
  'The ice cream man',
  'Love',
  'Stank breath',
  'Living in the dumpster',
  'Having a baby',
  'Shoplifting',
  'My father, who is a walrus',
  'The dentist',
  'Aunt Linda',
  'One tough mama',
  'Releasing the falcons',
  'Literally ruining my life',
  'Flushing myself down the toilet',
  'Fire farts',
  'Lice',
  'A killer clown',
  'Blossoming into a beautiful young man',
  'Wiping my butt',
  'Saying mean stuff and making people feel bad',
  'Beyoncé',
  'A truck',
  'Only beans',
  'The beautiful potato',
  'Legs',
  "The woman I'm going to marry one day",
  'Unleashing a hell demon that will destroy our world',
  'Feminism',
  'Lighting stuff on fire',
  'Turning 40',
  'Getting a skull tattoo',
  'An invisible giant who takes giant, visible poops',
  'A cowboy who is half boy, half cow',
  'The longest tongue in the world',
  'Josh',
  'Locking Mother in the pantry',
  'Ariana Grande',
  'A glorious beard',
  'All of my teeth falling out',
  'Floating through the void of space and time',
  'Farting, barfing, and passing out',
  "Flamin' Hot Cheetos",
  'Snakes',
  'Free ice cream, yo',
  'Screaming and screaming and never waking up',
  'Running away from home',
  'Using my butt as a microwave',
  "Glen's fabulous body",
  'Gluten',
  'Wakanda',
  'Many wolves',
  'One long hair growing out of a mole',
  'A butt that eats underwear',
  'Poo-poo',
  'Mooing',
  'Robbing a bank',
  'Punching everyone',
  'How much wood a woodchuck would chuck if a woodchuck could chuck wood',
  'Swords',
  "Kevin's mom",
  'Getting scalded in the face with hot beans',
  'Chest hair',
  'My annoying sister',
  'Getting slapped with a fish',
  'Harry Potter',
  'Peeing sand',
  'Being French, hoh-hoh-hoh',
  'Guacamole',
  'Getting naked',
  'A super angry cat I found outside',
  'Slappy Spatchy, the game where you slap each other with spatulas',
  'A pregnant person',
  'A bunch of dead squirrels on a trampoline',
  'Grandma panties',
  'Thick, nasty burps',
  'Having no bones',
  'Famous peanut scientist George Washington Carver',
  "Saving up my boogers for ten years and then building the world's largest booger",
  'The president',
  'A hug',
  'The Dark Lord',
  'Being super serious right now',
  'Freeing a fart from its butt prison',
  'An order of mozzarella sticks',
  'Fake news',
  'The baby',
  'Learn more at www.SlappySpatchy.com',
  'Like a million alligators',
  'Big, slappy hands',
  'Beer',
  'Spit',
  'The fifth graders',
  'Licking a goat',
  'A flamethrower',
  'Drama!',
  "Old Jim's Steamy Butt Sauce",
  'Going to the emergency room',
  'Sitting atop a pile of tuna, like some kind of tuna queen',
  'A Pringle',
  'Never showering',
  'Naptime',
  'The gym teacher',
  'Coming back from the dead',
  'Burning books',
  'Falling in love',
  'Tossed salads and scrambled eggs',
  'Building a ladder of hot dogs to the moon',
  'Practicing kissing',
  'Eating a lightning bug to gain its lightning powers',
  'Slowly turning into cheese',
  'Whispering secrets to my best friend, Turkey',
  'Ear wax',
  'Knives',
  'Stuff',
  'Taking a selfie',
  'Dancing with my son',
  'Punching a guy through a wall',
  'Nipples',
  'Cat pee',
  'Dump cake',
  'Billie Eilish',
  'Steven Universe',
  'Elegant party hats',
  'Santa Claus',
  'The gluteus maximus',
  'Baby Yoda',
  "Peeing in the cat's litter box",
  'A big sad dragon with no friends',
  'A big whiny cry-baby',
  'Seymour Butts',
  'The bus driver',
  'Getting run over by a train',
  'Spinning and barfing',
  "Some freakin' privacy",
  'Butt hair',
  'Having many husbands',
  'Making the bathroom smell',
  'Coffee',
  'Anime',
  "The sweet honking of Karen's bassoon",
  'Pooping in a bag and lighting it on fire',
  'Space lasers',
  'Being dead',
  'Pooping barf forever',
  'FOOOOD FIIIIIIIIIIIIIIIIIGHT!!!',
  'Wearing high heels',
  'A long, long snake',
  'Getting trampled by horses',
  'The babysitter',
  'The lunch lady',
  'Peeing on my poopy',
  'Meatballs, meatballs, meatballs!',
  'Finding Waldo',
  "Going around sniffing people's armpits",
  'The divorce',
  'Diaper beans',
  'Cigarettes',
  'Getting my ponytail stuck in my butt',
  "Looking into people's windows",
  'Sucking at life',
  'Crossbows',
  'Evil',
  'A big rock',
  'Rubbing lotion on a hairless cat',
  'Nasty Cousin Amber',
  'Tongue kissing',
  'Abraham Lincoln',
  'Covering myself with ketchup and mustard because I am hot dog',
  'Hot, fresh doodies',
  'Feet',
  'Sadness',
  'Going beast mode',
  'An owl that hates you',
  'A doll that pees real pee!',
  'A naked lady in a painting',
  'Chunks',
  'Some weird guy',
  'Getting a girlfriend',
  'Falling in love with a hot dog',
  'Throwing stuff at other stuff',
  'Hogs',
  "A turd that just won't flush",
  'The entire state of Texas',
  'Showing everyone my butt',
  'My big donkey brother',
  'The huge, stupid moon',
  'Math',
  'Pee-pee',
  'Dinner',
  'Butthole',
  'Smelling like onions',
  'Being fake',
  'Peer pressure',
  'Peeing in my backpack',
  'Bad parenting',
  "Mom's butt",
  "One weird lookin' toe",
  'You',
  'Boys',
  'Sitting on a cake',
  'Teaching a chicken to kill',
  'The middle finger',
  'A bra',
  'Being famous on YouTube',
  'Cream',
  'Having no friends',
  "Peeing into everyone's mouth",
  'Gluing my butt cheeks together',
  'How school slowly breaks your spirit and drains your will to live',
  'A Pokémon named "Jim"',
  "True love's kiss",
  'Total crap',
  'Cool sunglasses',
  'Literally dying from the smell of a fart',
  'Snot bubbles',
  'Doing crimes and going to jail',
  'This goat, who is my friend',
  'Aliens',
  'School',
  'A cow',
  'The terrible winter of 1609',
  'Getting sucked into a jet engine',
  'Not breathing',
  'Licking a used band-aid',
  'Having to pee so bad',
  'Braiding my armpit hair',
  'Waking up inside of a spider web',
  'Blasting farts in the powder room',
  'The black half of Barack Obama',
  'The white half of Barack Obama',
  'A face full of horse cum',
  'Getting caught by the police and going to jail',
  "My dead son's baseball glove",
  'Ejaculating live bees and the bees are angry',
  'Western standards of beauty',
  'Getting eaten alive by Guy Fieri',
  'Blowjobs for everyone',
  'Blackface',
  'Butt stuff',
  'Some shit-hot guitar licks',
  'Social justice warriors with flamethrowers of compassion',
  'Deez nuts',
  'An unforgettable quincea├▒era',
  'September 11th, 2001',
  "Daddy's credit card",
  'A one-way ticket to Gary, Indiana',
  'An uninterrupted history of imperialism and exploitation',
  'P.F. Change himself',
  "Cutting off a flamingo's legs with garden shears",
  'A giant powdery manbaby',
  "Anal fissures like you wouldn't believe",
  'Not believing in giraffes',
  'Getting drive-by shot',
  'A team of lawyers',
  'AIDS monkeys',
  'Wearing glasses and sounding smart',
  'Slowly easing down onto a cucumber',
  'A whole new kind of porn',
  '40 acres and a mule',
  'Boring vaginal sex',
  "Genghis Khan's DNA",
  'The tiger that killed my father',
  "My boyfriend's stupid penis",
  "Changing a person's mind with logic and facts",
  'Child support payments',
  'The passage of time',
  'Going to a high school reunion on ketamine',
  'A reason not to commit suicide',
  'Russian super-tuberculosis',
  'A mouthful of potato salad',
  'All these decorative pillows',
  'Figuring out how to have sex with a dolphin',
  'Being worshipped as the one true God',
  'The basic suffering that pervades all of existence',
  'The ghost of Marlon Brando',
  'Out-of-this-world bazongas',
  'Ancient Athenian boy-fucking',
  'A crazy little thing called love',
  'A zero-risk way to make $2,000 from home',
  'Seeing my village burned and my family slaughtered before my eyes',
  'Being paralyzed from the neck down',
  'Backwards knees',
  'Having been dead for a while',
  'My first period',
  'Vegetarian options',
  'The Abercrombie & Fitch lifestyle',
  'The unbelievable world of mushrooms',
  'Being nine years old',
  'The eight gay warlocks who dictate the rules of fashion',
  'The swim team, all at once',
  'Denzel',
  'Unrelenting genital punishment',
  "Mom's new boyfriend",
  'A disappointing salad',
  'A powered exoskeleton',
  'Ennui',
  'Oil!',
  'Giant sperm from outer space',
  'Doing the right stuff to her nipples',
  'Too much cocaine',
  "Seeing things from Hitler's perspective",
  'A big black dick',
  'A beached whale',
  'A bloody pacifier',
  'A crappy little hand',
  'A low standard of living',
  'A nuanced critique',
  'Panty raids',
  'A passionate Latino lover',
  'A rival dojo',
  'A web of lies',
  'A woman scorned',
  'Apologizing',
  'A plunger to the face',
  'Neil Patrick Harris',
  'Beating your wives',
  'Shaft',
  'Bosnian chicken farmers',
  'Nubile slave boys',
  'Carnies',
  'Coughing into a vagina',
  'Suicidal thoughts',
  'The ooze',
  'Deflowering the princess',
  'Dorito breath',
  'Eating an albino',
  'Enormous Scandinavian women',
  'Fabricating statistics',
  'Finding a skeleton',
  'Gandalf',
  'Genetically engineered super-soldiers',
  "George Clooney's musk",
  'Getting abducted by Peter Pan',
  'Getting in her pants, politely',
  'Gladiatorial combat',
  'Clenched butt cheeks',
  'Hipsters',
  'Historical revisionism',
  'Insatiable bloodlust',
  'Jafar',
  'Jean-Claude Van Damme',
  'Just the tip',
  'Mad hacky-sack skills',
  'Leveling up',
  'Literally eating shit',
  'Making the penises kiss',
  '24-hour media coverage',
  'Medieval Times© Dinner & Tournament',
  'Moral ambiguity',
  'My machete',
  'One thousand Slim Jims',
  'Ominous background music',
  'Overpowering your father',
  'Stockholm Syndrome',
  'Quiche',
  'Quivering jowls',
  'Revenge fucking',
  "Ripping into a man's chest and pulling out his still-beating heart",
  'Ryan Gosling riding in on a white horse',
  'Scrotum tickling',
  'Sexual humiliation',
  'Sexy Siamese twins',
  'Saliva',
  'Space muffins',
  'Statistically validated stereotypes',
  'Sudden Poop Explosion Disease',
  'The boners of the elderly',
  'The economy',
  'Syphilitic insanity',
  'The Gulags',
  'The harsh light of day',
  'The hiccups',
  'The shambling corpse of Larry King',
  'The four arms of Vishnu',
  'Being a busy adult with many important things to do',
  'Tripping balls',
  'Words, words, words',
  "Zeus's sexual appetites",
  '10 Incredible Facts About the Anus',
  'A Native American who solves crimes by going into the spirit world',
  'A Ugandan warlord',
  'A bunch of idiots playing a card game instead of interacting like normal humans',
  "A dance move that's just sex",
  'A fart',
  'A for-real lizard that spits blood from its eyes',
  'A gender identity that can only be conveyed through slam poetry',
  'A hopeless amount of spiders',
  'A kiss on the lips',
  'A manhole',
  'A sex comet from Neptune that plunges the Earth into eternal sexiness',
  'A sex goblin with a carnival penis',
  'A shiny rock that proves I love you',
  'Actual mutants with medical conditions and no superpowers',
  'Africa',
  'All the single ladies',
  'Almost giving money to a homeless person',
  'Ambiguous sarcasm',
  'An interracial handshake',
  'Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of night',
  'Ass to mouth',
  'Blackula',
  'Bouncing up and down',
  'Calculating every mannerism so as not to suggest homosexuality',
  'Child Protective Services',
  'Crazy opium eyes',
  'Dem titties',
  'Depression',
  'Doo-doo',
  'Drinking responsibly',
  'Exploding pigeons',
  'Falling into the toilet',
  'Finally finishing off the Indians',
  'Fucking a corpse back to life',
  'Grammar nazis who are also regular Nazis',
  'How awesome I am',
  'Injecting speed into one arm and horse tranquilizer into the other',
  'Interspecies marriage',
  'Jizz',
  'Khakis',
  'Lots and lots of abortions',
  'Moderate-to-severe joint pain',
  "My dad's dumb fucking face",
  'My sex dungeon',
  'My worthless son',
  "Neil Diamond's Greatest Hits",
  'No clothes on, penis in vagina',
  'Party Mexicans',
  'Prince Ali, fabulous he, Ali Ababwa',
  'Smoking crack, for instance',
  "Snorting coke off a clown's boner",
  'Some sort of Asian',
  'Sports',
  "Stuffing a child's face with Fun Dip® until he starts having fun",
  'Sugar madness',
  'The complex geopolitical quagmire that is the Middle East',
  'The euphoric rush of strangling a drifter',
  'The peaceful and nonthreatening rise of China',
  'The safe word',
  'The secret formula for ultimate female satisfaction',
  'The size of my penis',
  'The tiniest shred of evidence that God is real',
  'Three consecutive seconds of happiness',
  'Unquestioning obedience',
  'What Jesus would do',
  'Whatever a McRib® is made of',
  'Whispering all sexy',
  'A bigger, blacker dick',
  "The mere concept of Applebee's®",
  'A sad fat dragon with no friends',
  'Catastrophic urethral trauma',
  "Hillary Clinton's death stare",
  'Existing',
  'A pinata full of scorpions',
  'Swiftly achieving orgasm',
  "Daddy's belt",
  'Double penetration',
  'Weapons-grade plutonium',
  'Some really fucked-up shit',
  'Subduing a grizzly bear and making her your wife',
  'Rising from the grave',
  'The mixing of the races',
  "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes",
  'Scrotal frostbite',
  'All of this blood',
  'Loki, the trickster god',
  'Whining like a little bitch',
  'Pumping out a baby every nine months',
  'Tongue',
  'Upgrading homeless people to mobile hotspots',
  'Wearing an octopus for a hat',
  'An unhinged ferris wheel rolling toward the sea',
  'Living in a trashcan',
  'The corporations',
  'A magic hippie love cloud',
  'Fuck Mountain',
  "Survivor's guilt",
  'Getting hilariously gang-banged by the Blue Man Group',
  'Jeff Goldblum',
  'Making a friend',
  'A soulful rendition of "Ol\' Man River"',
  'Intimacy problems',
  'A sweaty, panting leather daddy',
  'Spring break!',
  'Being awesome at sex',
  'Dining with cardboard cutouts of the cast of \\"Friends\\"',
  'Another shot of morphine',
  "Beefin' over turf",
  'A squadron of moles wearing aviator goggles',
  'Bullshit',
  'The Google',
  'Pretty Pretty Princess Dress-Up Board Game®',
  'The new Radiohead album',
  'An army of skeletons',
  'A man in yoga pants with a ponytail and feather earrings',
  'Mild autism',
  'Nunchuck moves',
  'Whipping a disobedient slave',
  'An ether-soaked rag',
  'A sweet spaceship',
  'A 55-gallon drum of lube',
  'Special musical guest, Cher',
  'The human body',
  'Boris the Soviet Love Hammer',
  'The grey nutrient broth that sustains Mitt Romney',
  'Tiny nipples',
  'Power',
  'Oncoming traffic',
  'A dollop of sour cream',
  'A slightly shittier parallel universe',
  'My first kill',
  'Graphic violence, adult language, and some sexual content',
  'Fetal alcohol syndrome',
  'The day the birds attacked',
  'One Ring to rule them all',
  "Grandpa's ashes",
  'Basic human decency',
  'A Burmese tiger pit',
  'Death by Steven Seagal',
  'A bass drop so huge it tears the starry vault asunder to reveal the face of God',
  'Growing up chained to a radiator in perpetual darkness',
  'Shitting all over the floor like a bad, bad girl',
  'A buttload of candy',
  'Sucking all the milk out of a yak',
  'Bullets',
  'A man who is so cool that he rides on a motorcycle',
  'Sudden penis loss',
  'Getting all offended',
  'Crying and shitting and eating spaghetti',
  'One unforgettable night of passion',
  'Being popular and good at sports',
  "Filling a man's anus with concrete",
  'Two whales fucking the shit out of eachother',
  'Cool, releatable cancer teens',
  'The amount of gay I am',
  'A possible Muslim',
  'Unsheathing my massive horse cock',
  'A bowl of gourds',
  'The male gaze',
  'Ripping a dog in half',
  'A constant need for validation',
  'Meaningless sex',
  'Such a big boy',
  'Throwing stones at a man until he dies',
  'Cancer',
  'Eating together like a god damn family for once',
  'Cute boys',
  'Pussy',
  'Being a terrible mother',
  'Never having sex again',
  'A pizza guy who fucked up',
  'A whole lotta woman',
  'The all-new Nissan Pathfinder with 0.9% APR financing!',
  'A peyote-fueled vision quest',
  'Kale',
  'Breastfeeding a ten year old',
  'Crippling social anxiety',
  'Immortality cream',
  'Texas',
  'Teaching a girl how to handjob the penis',
  'A turd',
  'Shapes and colors',
  'Whatever you wish, mother',
  'The haunting stare of an Iraqi child',
  'Robots who just want to party',
  'A self-microwaving burrito',
  "Forgetting grandma's first name",
  'Our new Buffalo Chicken Dippers®!',
  'Treasures beyond your wildest dreams',
  'The sweet song of sword against and the braying of mighty war beasts',
  'Walking into a glass door',
  'The color "puce"',
  "Every ounce of charisma left in Mick Jagger's tired body",
  'The eighth graders',
  'Setting my balls on fire and cartwheeling to Ohio',
  "Gwyneth Paltrow's opinions",
  'Turning the rivers red with the blood of infidels',
  'Rabies',
  'Important news about Taylor Swift',
  "Ejaculating inside another man's wife",
  'Owls, the perfect predator',
  'Being John Malkovich',
  'Bathing in moonsblood and dancing around the ancient oak',
  'An oppressed people with a vibrant culture',
  'An overwhelming variety of cheeses',
  'Reading the entire End-User License Agreement',
  'Morpheus',
  "Peeing into a girl's butt to make a baby",
  "Generally having no idea of what's going on",
  'No longer finding any Cards Against Humanity card funny',
  'The primal, ball-slapping sex your parents are having right now',
  'A cat video so cute that your eyes roll back and your spine slides out of your anus',
  'Cock',
  'A cop who is also a dog',
  'Dying alone and in pain',
  'Gay aliens',
  'The way white people is',
  'Reverse cowgirl',
  "The Quesadilla Explosion Salad™ from Chili's©",
  'Actually getting shot, for real',
  'Not having sex',
  'Vietnam flashbacks',
  'Running naked through a mall, pissing and shitting everywhere',
  'Warm, velvety muppet sex',
  'Self-flagellation',
  'The systematic destruction of an entire people and their way of life',
  'Samuel L Jackson',
  'A boo-boo',
  'Going around punching people',
  'The entire Internet',
  'Some kind of bird-man',
  'Chugging a lava lamp',
  'Having sex on top of a pizza',
  'Indescribable loneliness',
  'An ass disaster',
  'Shutting the fuck up',
  'All my friends dying',
  'Putting an entire peanut butter and jelly sandwich into the VCR',
  'Spending lots of money',
  'Some douche with an acoustic guitar',
  'Flying robots that kill people',
  'A greased-up Matthew McConaughey',
  'An unstoppable wave of fire ants',
  'Not contributing to society in any meaningful way',
  'An all-midget production of Shakespeare\'s "Richard III"',
  'Screaming like a maniac',
  'The moist, demanding chasm of his mouth',
  'Filling every orifice with butterscotch pudding',
  'Unlimited soup, salad, and breadsticks',
  'Crying into the pages of Sylvia Plath',
  'Velcro™',
  'A PowerPoint presentation',
  'A surprising amount of hair',
  "Eating Tom Selleck's mustache to gain his powers",
  'Roland the Farter, flatulist to the king',
  'That ass',
  'A pile of squirming bodies',
  'Buying the right pants to be cool',
  'Blood farts',
  'Three months in the hole',
  'A botched circumcision',
  'The Land of Chocolate',
  'Slapping a racist old lady',
  'A lamprey swimming up the toilet and latching onto your taint',
  'Jumping out at people',
  'A black male in his early 20s, last seen wearing a hoodie',
  "Mufasa's death scene",
  'Bill Clinton, naked on a bearskin rug with a saxophone',
  'Demonic possession',
  'The Harlem Globetrotters',
  'Vomiting mid-blowjob',
  'My manservant, Claude',
  'Having shotguns for legs',
  'Letting everyone down',
  'A spontaneous conga line',
  'A vagina that leads to another dimension',
  'Disco fever',
  'Getting your dick stuck in a Chinese finger trap with another dick',
  'Fisting',
  'The thin veneer of situational causality that underlies porn',
  "Girls that always be textin'",
  'Blowing some dudes in an alley',
  'Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy',
  'Sneezing, farting, and coming at the same time',
]
